
namespace WareHouse.Forms
{
    partial class LoginForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoginForm));
            this.Elipse = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.FormDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.MainPanel = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.LogoBox = new System.Windows.Forms.PictureBox();
            this.RusButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.EngButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ExitButton = new System.Windows.Forms.Button();
            this.SignUpThinButton = new Bunifu.Framework.UI.BunifuThinButton2();
            this.ForgotPasswordThinButton = new Bunifu.Framework.UI.BunifuThinButton2();
            this.ErrorPanel = new System.Windows.Forms.Panel();
            this.ErrorTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LoginButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PasswordTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.UserNameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.WorkerButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.UserButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ToolTip = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.MainPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.LogoBox)).BeginInit();
            this.ErrorPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // Elipse
            // 
            this.Elipse.ElipseRadius = 0;
            this.Elipse.TargetControl = this;
            // 
            // FormDock
            // 
            this.FormDock.AllowFormDragging = true;
            this.FormDock.AllowFormDropShadow = true;
            this.FormDock.AllowFormResizing = true;
            this.FormDock.AllowHidingBottomRegion = true;
            this.FormDock.AllowOpacityChangesWhileDragging = false;
            this.FormDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.FormDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.FormDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.FormDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.FormDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.FormDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.FormDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.FormDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.FormDock.BorderOptions.RightBorder.ShowBorder = true;
            this.FormDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.FormDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.FormDock.BorderOptions.TopBorder.ShowBorder = true;
            this.FormDock.ContainerControl = this;
            this.FormDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.FormDock.DockingIndicatorsOpacity = 0.5D;
            this.FormDock.DockingOptions.DockAll = true;
            this.FormDock.DockingOptions.DockBottomLeft = true;
            this.FormDock.DockingOptions.DockBottomRight = true;
            this.FormDock.DockingOptions.DockFullScreen = true;
            this.FormDock.DockingOptions.DockLeft = true;
            this.FormDock.DockingOptions.DockRight = true;
            this.FormDock.DockingOptions.DockTopLeft = true;
            this.FormDock.DockingOptions.DockTopRight = true;
            this.FormDock.FormDraggingOpacity = 0.9D;
            this.FormDock.ParentForm = this;
            this.FormDock.ShowCursorChanges = true;
            this.FormDock.ShowDockingIndicators = true;
            this.FormDock.TitleBarOptions.AllowFormDragging = true;
            this.FormDock.TitleBarOptions.BunifuFormDock = this.FormDock;
            this.FormDock.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.FormDock.TitleBarOptions.TitleBarControl = null;
            this.FormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // MainPanel
            // 
            this.MainPanel.BackColor = System.Drawing.Color.Transparent;
            resources.ApplyResources(this.MainPanel, "MainPanel");
            this.MainPanel.BorderRadius = 1;
            this.MainPanel.Controls.Add(this.LogoBox);
            this.MainPanel.Controls.Add(this.RusButton);
            this.MainPanel.Controls.Add(this.EngButton);
            this.MainPanel.Controls.Add(this.ExitButton);
            this.MainPanel.Controls.Add(this.SignUpThinButton);
            this.MainPanel.Controls.Add(this.ForgotPasswordThinButton);
            this.MainPanel.Controls.Add(this.ErrorPanel);
            this.MainPanel.Controls.Add(this.LoginButton);
            this.MainPanel.Controls.Add(this.PasswordTextBox);
            this.MainPanel.Controls.Add(this.UserNameTextBox);
            this.MainPanel.Controls.Add(this.WorkerButton);
            this.MainPanel.Controls.Add(this.UserButton);
            this.MainPanel.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(143)))), ((int)(((byte)(166)))));
            this.MainPanel.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(143)))), ((int)(((byte)(166)))));
            this.MainPanel.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.MainPanel.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.MainPanel.Name = "MainPanel";
            this.MainPanel.Quality = 10;
            this.ToolTip.SetToolTip(this.MainPanel, "");
            this.ToolTip.SetToolTipIcon(this.MainPanel, null);
            this.ToolTip.SetToolTipTitle(this.MainPanel, "");
            // 
            // LogoBox
            // 
            this.LogoBox.Image = global::WareHouse.Properties.Resources.LogoIcon;
            resources.ApplyResources(this.LogoBox, "LogoBox");
            this.LogoBox.Name = "LogoBox";
            this.LogoBox.TabStop = false;
            this.ToolTip.SetToolTip(this.LogoBox, "");
            this.ToolTip.SetToolTipIcon(this.LogoBox, null);
            this.ToolTip.SetToolTipTitle(this.LogoBox, "");
            // 
            // RusButton
            // 
            this.RusButton.AllowAnimations = true;
            this.RusButton.AllowMouseEffects = true;
            this.RusButton.AllowToggling = false;
            this.RusButton.AnimationSpeed = 200;
            this.RusButton.AutoGenerateColors = false;
            this.RusButton.AutoRoundBorders = false;
            this.RusButton.AutoSizeLeftIcon = true;
            this.RusButton.AutoSizeRightIcon = true;
            this.RusButton.BackColor = System.Drawing.Color.Transparent;
            this.RusButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            resources.ApplyResources(this.RusButton, "RusButton");
            this.RusButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RusButton.ButtonText = "RUS";
            this.RusButton.ButtonTextMarginLeft = 0;
            this.RusButton.ColorContrastOnClick = 45;
            this.RusButton.ColorContrastOnHover = 45;
            this.RusButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = false;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = false;
            borderEdges1.TopRight = true;
            this.RusButton.CustomizableEdges = borderEdges1;
            this.RusButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RusButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RusButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RusButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RusButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.RusButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.RusButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RusButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RusButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RusButton.IconMarginLeft = 11;
            this.RusButton.IconPadding = 10;
            this.RusButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RusButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RusButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RusButton.IconSize = 25;
            this.RusButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(225)))));
            this.RusButton.IdleBorderRadius = 30;
            this.RusButton.IdleBorderThickness = 2;
            this.RusButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.RusButton.IdleIconLeftImage = null;
            this.RusButton.IdleIconRightImage = null;
            this.RusButton.IndicateFocus = false;
            this.RusButton.Name = "RusButton";
            this.RusButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RusButton.OnDisabledState.BorderRadius = 30;
            this.RusButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RusButton.OnDisabledState.BorderThickness = 2;
            this.RusButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RusButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RusButton.OnDisabledState.IconLeftImage = null;
            this.RusButton.OnDisabledState.IconRightImage = null;
            this.RusButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RusButton.onHoverState.BorderRadius = 30;
            this.RusButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RusButton.onHoverState.BorderThickness = 2;
            this.RusButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RusButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RusButton.onHoverState.IconLeftImage = null;
            this.RusButton.onHoverState.IconRightImage = null;
            this.RusButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(225)))));
            this.RusButton.OnIdleState.BorderRadius = 30;
            this.RusButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RusButton.OnIdleState.BorderThickness = 2;
            this.RusButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.RusButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.RusButton.OnIdleState.IconLeftImage = null;
            this.RusButton.OnIdleState.IconRightImage = null;
            this.RusButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RusButton.OnPressedState.BorderRadius = 30;
            this.RusButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RusButton.OnPressedState.BorderThickness = 2;
            this.RusButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RusButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RusButton.OnPressedState.IconLeftImage = null;
            this.RusButton.OnPressedState.IconRightImage = null;
            this.RusButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RusButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RusButton.TextMarginLeft = 0;
            this.RusButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.RusButton, "");
            this.ToolTip.SetToolTipIcon(this.RusButton, null);
            this.ToolTip.SetToolTipTitle(this.RusButton, "");
            this.RusButton.UseDefaultRadiusAndThickness = true;
            this.RusButton.Click += new System.EventHandler(this.RusButton_Click);
            // 
            // EngButton
            // 
            this.EngButton.AllowAnimations = true;
            this.EngButton.AllowMouseEffects = true;
            this.EngButton.AllowToggling = false;
            this.EngButton.AnimationSpeed = 200;
            this.EngButton.AutoGenerateColors = false;
            this.EngButton.AutoRoundBorders = false;
            this.EngButton.AutoSizeLeftIcon = true;
            this.EngButton.AutoSizeRightIcon = true;
            this.EngButton.BackColor = System.Drawing.Color.Transparent;
            this.EngButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            resources.ApplyResources(this.EngButton, "EngButton");
            this.EngButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EngButton.ButtonText = "ENG";
            this.EngButton.ButtonTextMarginLeft = 0;
            this.EngButton.ColorContrastOnClick = 45;
            this.EngButton.ColorContrastOnHover = 45;
            this.EngButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = false;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = false;
            this.EngButton.CustomizableEdges = borderEdges2;
            this.EngButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.EngButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.EngButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EngButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.EngButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.EngButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.EngButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.EngButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.EngButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.EngButton.IconMarginLeft = 11;
            this.EngButton.IconPadding = 10;
            this.EngButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.EngButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.EngButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.EngButton.IconSize = 25;
            this.EngButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(225)))));
            this.EngButton.IdleBorderRadius = 30;
            this.EngButton.IdleBorderThickness = 2;
            this.EngButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.EngButton.IdleIconLeftImage = null;
            this.EngButton.IdleIconRightImage = null;
            this.EngButton.IndicateFocus = false;
            this.EngButton.Name = "EngButton";
            this.EngButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.EngButton.OnDisabledState.BorderRadius = 30;
            this.EngButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EngButton.OnDisabledState.BorderThickness = 2;
            this.EngButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EngButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.EngButton.OnDisabledState.IconLeftImage = null;
            this.EngButton.OnDisabledState.IconRightImage = null;
            this.EngButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EngButton.onHoverState.BorderRadius = 30;
            this.EngButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EngButton.onHoverState.BorderThickness = 2;
            this.EngButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EngButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.EngButton.onHoverState.IconLeftImage = null;
            this.EngButton.onHoverState.IconRightImage = null;
            this.EngButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(225)))));
            this.EngButton.OnIdleState.BorderRadius = 30;
            this.EngButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EngButton.OnIdleState.BorderThickness = 2;
            this.EngButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.EngButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.EngButton.OnIdleState.IconLeftImage = null;
            this.EngButton.OnIdleState.IconRightImage = null;
            this.EngButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.EngButton.OnPressedState.BorderRadius = 30;
            this.EngButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EngButton.OnPressedState.BorderThickness = 2;
            this.EngButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.EngButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.EngButton.OnPressedState.IconLeftImage = null;
            this.EngButton.OnPressedState.IconRightImage = null;
            this.EngButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.EngButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.EngButton.TextMarginLeft = 0;
            this.EngButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.EngButton, "");
            this.ToolTip.SetToolTipIcon(this.EngButton, null);
            this.ToolTip.SetToolTipTitle(this.EngButton, "");
            this.EngButton.UseDefaultRadiusAndThickness = true;
            this.EngButton.Click += new System.EventHandler(this.EngButton_Click);
            // 
            // ExitButton
            // 
            this.ExitButton.FlatAppearance.BorderSize = 0;
            resources.ApplyResources(this.ExitButton, "ExitButton");
            this.ExitButton.Image = global::WareHouse.Properties.Resources.exit_button;
            this.ExitButton.Name = "ExitButton";
            this.ExitButton.TabStop = false;
            this.ToolTip.SetToolTip(this.ExitButton, "");
            this.ToolTip.SetToolTipIcon(this.ExitButton, null);
            this.ToolTip.SetToolTipTitle(this.ExitButton, "");
            this.ExitButton.UseVisualStyleBackColor = true;
            this.ExitButton.Click += new System.EventHandler(this.ExitButton_Click);
            // 
            // SignUpThinButton
            // 
            this.SignUpThinButton.ActiveBorderThickness = 1;
            this.SignUpThinButton.ActiveCornerRadius = 20;
            this.SignUpThinButton.ActiveFillColor = System.Drawing.Color.Transparent;
            this.SignUpThinButton.ActiveForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.SignUpThinButton.ActiveLineColor = System.Drawing.Color.Transparent;
            this.SignUpThinButton.BackColor = System.Drawing.Color.Transparent;
            resources.ApplyResources(this.SignUpThinButton, "SignUpThinButton");
            this.SignUpThinButton.ButtonText = "Sign Up";
            this.SignUpThinButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.SignUpThinButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.SignUpThinButton.IdleBorderThickness = 1;
            this.SignUpThinButton.IdleCornerRadius = 20;
            this.SignUpThinButton.IdleFillColor = System.Drawing.Color.Transparent;
            this.SignUpThinButton.IdleForecolor = System.Drawing.Color.Transparent;
            this.SignUpThinButton.IdleLineColor = System.Drawing.Color.Transparent;
            this.SignUpThinButton.Name = "SignUpThinButton";
            this.SignUpThinButton.TabStop = false;
            this.SignUpThinButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ToolTip.SetToolTip(this.SignUpThinButton, "");
            this.ToolTip.SetToolTipIcon(this.SignUpThinButton, null);
            this.ToolTip.SetToolTipTitle(this.SignUpThinButton, "");
            this.SignUpThinButton.Click += new System.EventHandler(this.SignUpThinButton_Click);
            // 
            // ForgotPasswordThinButton
            // 
            this.ForgotPasswordThinButton.ActiveBorderThickness = 1;
            this.ForgotPasswordThinButton.ActiveCornerRadius = 20;
            this.ForgotPasswordThinButton.ActiveFillColor = System.Drawing.Color.Transparent;
            this.ForgotPasswordThinButton.ActiveForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ForgotPasswordThinButton.ActiveLineColor = System.Drawing.Color.Transparent;
            this.ForgotPasswordThinButton.BackColor = System.Drawing.Color.Transparent;
            resources.ApplyResources(this.ForgotPasswordThinButton, "ForgotPasswordThinButton");
            this.ForgotPasswordThinButton.ButtonText = "Forgot Password?";
            this.ForgotPasswordThinButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ForgotPasswordThinButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ForgotPasswordThinButton.IdleBorderThickness = 1;
            this.ForgotPasswordThinButton.IdleCornerRadius = 20;
            this.ForgotPasswordThinButton.IdleFillColor = System.Drawing.Color.Transparent;
            this.ForgotPasswordThinButton.IdleForecolor = System.Drawing.Color.Transparent;
            this.ForgotPasswordThinButton.IdleLineColor = System.Drawing.Color.Transparent;
            this.ForgotPasswordThinButton.Name = "ForgotPasswordThinButton";
            this.ForgotPasswordThinButton.TabStop = false;
            this.ForgotPasswordThinButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ToolTip.SetToolTip(this.ForgotPasswordThinButton, "");
            this.ToolTip.SetToolTipIcon(this.ForgotPasswordThinButton, null);
            this.ToolTip.SetToolTipTitle(this.ForgotPasswordThinButton, "");
            this.ForgotPasswordThinButton.Click += new System.EventHandler(this.ForgotPasswordThinButton_Click);
            // 
            // ErrorPanel
            // 
            this.ErrorPanel.Controls.Add(this.ErrorTextBox);
            resources.ApplyResources(this.ErrorPanel, "ErrorPanel");
            this.ErrorPanel.Name = "ErrorPanel";
            this.ToolTip.SetToolTip(this.ErrorPanel, "");
            this.ToolTip.SetToolTipIcon(this.ErrorPanel, null);
            this.ToolTip.SetToolTipTitle(this.ErrorPanel, "");
            // 
            // ErrorTextBox
            // 
            this.ErrorTextBox.AcceptsReturn = false;
            this.ErrorTextBox.AcceptsTab = false;
            this.ErrorTextBox.AnimationSpeed = 200;
            this.ErrorTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ErrorTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ErrorTextBox.BackColor = System.Drawing.Color.Transparent;
            resources.ApplyResources(this.ErrorTextBox, "ErrorTextBox");
            this.ErrorTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ErrorTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ErrorTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ErrorTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(76)))), ((int)(((byte)(103)))));
            this.ErrorTextBox.BorderRadius = 1;
            this.ErrorTextBox.BorderThickness = 1;
            this.ErrorTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ErrorTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ErrorTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.ErrorTextBox.DefaultText = "";
            this.ErrorTextBox.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(76)))), ((int)(((byte)(103)))));
            this.ErrorTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ErrorTextBox.HideSelection = true;
            this.ErrorTextBox.IconLeft = global::WareHouse.Properties.Resources.dialog_error_icon;
            this.ErrorTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ErrorTextBox.IconPadding = 10;
            this.ErrorTextBox.IconRight = null;
            this.ErrorTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ErrorTextBox.Lines = new string[0];
            this.ErrorTextBox.MaxLength = 32767;
            this.ErrorTextBox.Modified = false;
            this.ErrorTextBox.Multiline = true;
            this.ErrorTextBox.Name = "ErrorTextBox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ErrorTextBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ErrorTextBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ErrorTextBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(76)))), ((int)(((byte)(103)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(76)))), ((int)(((byte)(103)))));
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ErrorTextBox.OnIdleState = stateProperties4;
            this.ErrorTextBox.PasswordChar = '\0';
            this.ErrorTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ErrorTextBox.PlaceholderText = "Enter text";
            this.ErrorTextBox.ReadOnly = true;
            this.ErrorTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.ErrorTextBox.SelectedText = "";
            this.ErrorTextBox.SelectionLength = 0;
            this.ErrorTextBox.SelectionStart = 0;
            this.ErrorTextBox.ShortcutsEnabled = true;
            this.ErrorTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ErrorTextBox.TabStop = false;
            this.ErrorTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ErrorTextBox.TextMarginBottom = 0;
            this.ErrorTextBox.TextMarginLeft = 3;
            this.ErrorTextBox.TextMarginTop = 0;
            this.ErrorTextBox.TextPlaceholder = "Enter text";
            this.ToolTip.SetToolTip(this.ErrorTextBox, "");
            this.ToolTip.SetToolTipIcon(this.ErrorTextBox, null);
            this.ToolTip.SetToolTipTitle(this.ErrorTextBox, "");
            this.ErrorTextBox.UseSystemPasswordChar = false;
            this.ErrorTextBox.WordWrap = true;
            // 
            // LoginButton
            // 
            this.LoginButton.AllowAnimations = true;
            this.LoginButton.AllowMouseEffects = true;
            this.LoginButton.AllowToggling = false;
            this.LoginButton.AnimationSpeed = 200;
            this.LoginButton.AutoGenerateColors = false;
            this.LoginButton.AutoRoundBorders = false;
            this.LoginButton.AutoSizeLeftIcon = true;
            this.LoginButton.AutoSizeRightIcon = true;
            this.LoginButton.BackColor = System.Drawing.Color.Transparent;
            this.LoginButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            resources.ApplyResources(this.LoginButton, "LoginButton");
            this.LoginButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.ButtonText = "Login";
            this.LoginButton.ButtonTextMarginLeft = 0;
            this.LoginButton.ColorContrastOnClick = 45;
            this.LoginButton.ColorContrastOnHover = 45;
            this.LoginButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.LoginButton.CustomizableEdges = borderEdges3;
            this.LoginButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LoginButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LoginButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LoginButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LoginButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LoginButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.LoginButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LoginButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LoginButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LoginButton.IconMarginLeft = 11;
            this.LoginButton.IconPadding = 10;
            this.LoginButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LoginButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LoginButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LoginButton.IconSize = 25;
            this.LoginButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.LoginButton.IdleBorderRadius = 30;
            this.LoginButton.IdleBorderThickness = 2;
            this.LoginButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.LoginButton.IdleIconLeftImage = null;
            this.LoginButton.IdleIconRightImage = null;
            this.LoginButton.IndicateFocus = false;
            this.LoginButton.Name = "LoginButton";
            this.LoginButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LoginButton.OnDisabledState.BorderRadius = 30;
            this.LoginButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.OnDisabledState.BorderThickness = 2;
            this.LoginButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LoginButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LoginButton.OnDisabledState.IconLeftImage = null;
            this.LoginButton.OnDisabledState.IconRightImage = null;
            this.LoginButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LoginButton.onHoverState.BorderRadius = 30;
            this.LoginButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.onHoverState.BorderThickness = 2;
            this.LoginButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LoginButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LoginButton.onHoverState.IconLeftImage = null;
            this.LoginButton.onHoverState.IconRightImage = null;
            this.LoginButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.LoginButton.OnIdleState.BorderRadius = 30;
            this.LoginButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.OnIdleState.BorderThickness = 2;
            this.LoginButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.LoginButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.LoginButton.OnIdleState.IconLeftImage = null;
            this.LoginButton.OnIdleState.IconRightImage = null;
            this.LoginButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LoginButton.OnPressedState.BorderRadius = 30;
            this.LoginButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.OnPressedState.BorderThickness = 2;
            this.LoginButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LoginButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.LoginButton.OnPressedState.IconLeftImage = null;
            this.LoginButton.OnPressedState.IconRightImage = null;
            this.LoginButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LoginButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LoginButton.TextMarginLeft = 0;
            this.LoginButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.LoginButton, "");
            this.ToolTip.SetToolTipIcon(this.LoginButton, null);
            this.ToolTip.SetToolTipTitle(this.LoginButton, "");
            this.LoginButton.UseDefaultRadiusAndThickness = true;
            this.LoginButton.Click += new System.EventHandler(this.LoginButton_Click);
            // 
            // PasswordTextBox
            // 
            this.PasswordTextBox.AcceptsReturn = false;
            this.PasswordTextBox.AcceptsTab = false;
            this.PasswordTextBox.AnimationSpeed = 200;
            this.PasswordTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PasswordTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PasswordTextBox.BackColor = System.Drawing.Color.Transparent;
            resources.ApplyResources(this.PasswordTextBox, "PasswordTextBox");
            this.PasswordTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PasswordTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PasswordTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PasswordTextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.PasswordTextBox.BorderRadius = 1;
            this.PasswordTextBox.BorderThickness = 1;
            this.PasswordTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PasswordTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordTextBox.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 13F);
            this.PasswordTextBox.DefaultText = "";
            this.PasswordTextBox.FillColor = System.Drawing.Color.White;
            this.PasswordTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.PasswordTextBox.HideSelection = true;
            this.PasswordTextBox.IconLeft = global::WareHouse.Properties.Resources.password;
            this.PasswordTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordTextBox.IconPadding = 10;
            this.PasswordTextBox.IconRight = global::WareHouse.Properties.Resources.Hide_password;
            this.PasswordTextBox.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PasswordTextBox.Lines = new string[0];
            this.PasswordTextBox.MaxLength = 32767;
            this.PasswordTextBox.Modified = false;
            this.PasswordTextBox.Multiline = false;
            this.PasswordTextBox.Name = "PasswordTextBox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PasswordTextBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnIdleState = stateProperties8;
            this.PasswordTextBox.PasswordChar = '\0';
            this.PasswordTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PasswordTextBox.PlaceholderText = "Password";
            this.PasswordTextBox.ReadOnly = false;
            this.PasswordTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PasswordTextBox.SelectedText = "";
            this.PasswordTextBox.SelectionLength = 0;
            this.PasswordTextBox.SelectionStart = 0;
            this.PasswordTextBox.ShortcutsEnabled = true;
            this.PasswordTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PasswordTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PasswordTextBox.TextMarginBottom = 0;
            this.PasswordTextBox.TextMarginLeft = 10;
            this.PasswordTextBox.TextMarginTop = 0;
            this.PasswordTextBox.TextPlaceholder = "Password";
            this.ToolTip.SetToolTip(this.PasswordTextBox, "");
            this.ToolTip.SetToolTipIcon(this.PasswordTextBox, null);
            this.ToolTip.SetToolTipTitle(this.PasswordTextBox, "");
            this.PasswordTextBox.UseSystemPasswordChar = false;
            this.PasswordTextBox.WordWrap = true;
            this.PasswordTextBox.OnIconRightClick += new System.EventHandler(this.PasswordTextBox_OnIconRightClick);
            // 
            // UserNameTextBox
            // 
            this.UserNameTextBox.AcceptsReturn = false;
            this.UserNameTextBox.AcceptsTab = false;
            this.UserNameTextBox.AnimationSpeed = 200;
            this.UserNameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.UserNameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.UserNameTextBox.BackColor = System.Drawing.Color.Transparent;
            resources.ApplyResources(this.UserNameTextBox, "UserNameTextBox");
            this.UserNameTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.UserNameTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UserNameTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UserNameTextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.UserNameTextBox.BorderRadius = 1;
            this.UserNameTextBox.BorderThickness = 1;
            this.UserNameTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.UserNameTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.UserNameTextBox.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 13F);
            this.UserNameTextBox.DefaultText = "";
            this.UserNameTextBox.FillColor = System.Drawing.Color.White;
            this.UserNameTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.UserNameTextBox.HideSelection = true;
            this.UserNameTextBox.IconLeft = global::WareHouse.Properties.Resources.user;
            this.UserNameTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.UserNameTextBox.IconPadding = 10;
            this.UserNameTextBox.IconRight = null;
            this.UserNameTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.UserNameTextBox.Lines = new string[0];
            this.UserNameTextBox.MaxLength = 32767;
            this.UserNameTextBox.Modified = false;
            this.UserNameTextBox.Multiline = false;
            this.UserNameTextBox.Name = "UserNameTextBox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UserNameTextBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.UserNameTextBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UserNameTextBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UserNameTextBox.OnIdleState = stateProperties12;
            this.UserNameTextBox.PasswordChar = '\0';
            this.UserNameTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.UserNameTextBox.PlaceholderText = "Login / e-mail";
            this.UserNameTextBox.ReadOnly = false;
            this.UserNameTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.UserNameTextBox.SelectedText = "";
            this.UserNameTextBox.SelectionLength = 0;
            this.UserNameTextBox.SelectionStart = 0;
            this.UserNameTextBox.ShortcutsEnabled = true;
            this.UserNameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.UserNameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.UserNameTextBox.TextMarginBottom = 0;
            this.UserNameTextBox.TextMarginLeft = 10;
            this.UserNameTextBox.TextMarginTop = 0;
            this.UserNameTextBox.TextPlaceholder = "Login / e-mail";
            this.ToolTip.SetToolTip(this.UserNameTextBox, "");
            this.ToolTip.SetToolTipIcon(this.UserNameTextBox, null);
            this.ToolTip.SetToolTipTitle(this.UserNameTextBox, "");
            this.UserNameTextBox.UseSystemPasswordChar = false;
            this.UserNameTextBox.WordWrap = true;
            // 
            // WorkerButton
            // 
            this.WorkerButton.AllowAnimations = true;
            this.WorkerButton.AllowMouseEffects = true;
            this.WorkerButton.AllowToggling = false;
            this.WorkerButton.AnimationSpeed = 200;
            this.WorkerButton.AutoGenerateColors = false;
            this.WorkerButton.AutoRoundBorders = false;
            this.WorkerButton.AutoSizeLeftIcon = true;
            this.WorkerButton.AutoSizeRightIcon = true;
            this.WorkerButton.BackColor = System.Drawing.Color.Transparent;
            this.WorkerButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            resources.ApplyResources(this.WorkerButton, "WorkerButton");
            this.WorkerButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkerButton.ButtonText = "Worker";
            this.WorkerButton.ButtonTextMarginLeft = 0;
            this.WorkerButton.ColorContrastOnClick = 45;
            this.WorkerButton.ColorContrastOnHover = 45;
            this.WorkerButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = false;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = false;
            borderEdges4.TopRight = true;
            this.WorkerButton.CustomizableEdges = borderEdges4;
            this.WorkerButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.WorkerButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.WorkerButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.WorkerButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.WorkerButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.WorkerButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.WorkerButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.WorkerButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.WorkerButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.WorkerButton.IconMarginLeft = 11;
            this.WorkerButton.IconPadding = 10;
            this.WorkerButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.WorkerButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.WorkerButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.WorkerButton.IconSize = 25;
            this.WorkerButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.WorkerButton.IdleBorderRadius = 30;
            this.WorkerButton.IdleBorderThickness = 2;
            this.WorkerButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.WorkerButton.IdleIconLeftImage = null;
            this.WorkerButton.IdleIconRightImage = null;
            this.WorkerButton.IndicateFocus = false;
            this.WorkerButton.Name = "WorkerButton";
            this.WorkerButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.WorkerButton.OnDisabledState.BorderRadius = 30;
            this.WorkerButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkerButton.OnDisabledState.BorderThickness = 2;
            this.WorkerButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.WorkerButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.WorkerButton.OnDisabledState.IconLeftImage = null;
            this.WorkerButton.OnDisabledState.IconRightImage = null;
            this.WorkerButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.WorkerButton.onHoverState.BorderRadius = 30;
            this.WorkerButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkerButton.onHoverState.BorderThickness = 2;
            this.WorkerButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.WorkerButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.WorkerButton.onHoverState.IconLeftImage = null;
            this.WorkerButton.onHoverState.IconRightImage = null;
            this.WorkerButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.WorkerButton.OnIdleState.BorderRadius = 30;
            this.WorkerButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkerButton.OnIdleState.BorderThickness = 2;
            this.WorkerButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.WorkerButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.WorkerButton.OnIdleState.IconLeftImage = null;
            this.WorkerButton.OnIdleState.IconRightImage = null;
            this.WorkerButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.WorkerButton.OnPressedState.BorderRadius = 30;
            this.WorkerButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkerButton.OnPressedState.BorderThickness = 2;
            this.WorkerButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.WorkerButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.WorkerButton.OnPressedState.IconLeftImage = null;
            this.WorkerButton.OnPressedState.IconRightImage = null;
            this.WorkerButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.WorkerButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.WorkerButton.TextMarginLeft = 0;
            this.WorkerButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.WorkerButton, "");
            this.ToolTip.SetToolTipIcon(this.WorkerButton, global::WareHouse.Properties.Resources.message);
            this.ToolTip.SetToolTipTitle(this.WorkerButton, "");
            this.WorkerButton.UseDefaultRadiusAndThickness = true;
            this.WorkerButton.Click += new System.EventHandler(this.WorkerButton_Click);
            // 
            // UserButton
            // 
            this.UserButton.AllowAnimations = true;
            this.UserButton.AllowMouseEffects = true;
            this.UserButton.AllowToggling = false;
            this.UserButton.AnimationSpeed = 200;
            this.UserButton.AutoGenerateColors = false;
            this.UserButton.AutoRoundBorders = false;
            this.UserButton.AutoSizeLeftIcon = true;
            this.UserButton.AutoSizeRightIcon = true;
            this.UserButton.BackColor = System.Drawing.Color.Transparent;
            this.UserButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            resources.ApplyResources(this.UserButton, "UserButton");
            this.UserButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UserButton.ButtonText = "User";
            this.UserButton.ButtonTextMarginLeft = 0;
            this.UserButton.ColorContrastOnClick = 45;
            this.UserButton.ColorContrastOnHover = 45;
            this.UserButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = false;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = false;
            this.UserButton.CustomizableEdges = borderEdges5;
            this.UserButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.UserButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UserButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UserButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UserButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.UserButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.UserButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.UserButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.UserButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.UserButton.IconMarginLeft = 11;
            this.UserButton.IconPadding = 10;
            this.UserButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.UserButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.UserButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.UserButton.IconSize = 25;
            this.UserButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.UserButton.IdleBorderRadius = 30;
            this.UserButton.IdleBorderThickness = 2;
            this.UserButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.UserButton.IdleIconLeftImage = null;
            this.UserButton.IdleIconRightImage = null;
            this.UserButton.IndicateFocus = false;
            this.UserButton.Name = "UserButton";
            this.UserButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UserButton.OnDisabledState.BorderRadius = 30;
            this.UserButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UserButton.OnDisabledState.BorderThickness = 2;
            this.UserButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UserButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UserButton.OnDisabledState.IconLeftImage = null;
            this.UserButton.OnDisabledState.IconRightImage = null;
            this.UserButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UserButton.onHoverState.BorderRadius = 30;
            this.UserButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UserButton.onHoverState.BorderThickness = 2;
            this.UserButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UserButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.UserButton.onHoverState.IconLeftImage = null;
            this.UserButton.onHoverState.IconRightImage = null;
            this.UserButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.UserButton.OnIdleState.BorderRadius = 30;
            this.UserButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UserButton.OnIdleState.BorderThickness = 2;
            this.UserButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.UserButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.UserButton.OnIdleState.IconLeftImage = null;
            this.UserButton.OnIdleState.IconRightImage = null;
            this.UserButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UserButton.OnPressedState.BorderRadius = 30;
            this.UserButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UserButton.OnPressedState.BorderThickness = 2;
            this.UserButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UserButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.UserButton.OnPressedState.IconLeftImage = null;
            this.UserButton.OnPressedState.IconRightImage = null;
            this.UserButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.UserButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.UserButton.TextMarginLeft = 0;
            this.UserButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.UserButton, "");
            this.ToolTip.SetToolTipIcon(this.UserButton, global::WareHouse.Properties.Resources.message);
            this.ToolTip.SetToolTipTitle(this.UserButton, "");
            this.UserButton.UseDefaultRadiusAndThickness = true;
            this.UserButton.Click += new System.EventHandler(this.UserButton_Click);
            // 
            // ToolTip
            // 
            this.ToolTip.Active = true;
            this.ToolTip.AlignTextWithTitle = false;
            this.ToolTip.AllowAutoClose = false;
            this.ToolTip.AllowFading = true;
            this.ToolTip.AutoCloseDuration = 5000;
            this.ToolTip.BackColor = System.Drawing.SystemColors.Control;
            this.ToolTip.BorderColor = System.Drawing.Color.Gainsboro;
            this.ToolTip.ClickToShowDisplayControl = false;
            this.ToolTip.ConvertNewlinesToBreakTags = true;
            this.ToolTip.DisplayControl = null;
            this.ToolTip.EntryAnimationSpeed = 350;
            this.ToolTip.ExitAnimationSpeed = 200;
            this.ToolTip.GenerateAutoCloseDuration = false;
            this.ToolTip.IconMargin = 6;
            this.ToolTip.InitialDelay = 0;
            this.ToolTip.Name = "ToolTip";
            this.ToolTip.Opacity = 1D;
            this.ToolTip.OverrideToolTipTitles = false;
            this.ToolTip.Padding = new System.Windows.Forms.Padding(10);
            this.ToolTip.ReshowDelay = 100;
            this.ToolTip.ShowAlways = true;
            this.ToolTip.ShowBorders = false;
            this.ToolTip.ShowIcons = true;
            this.ToolTip.ShowShadows = true;
            this.ToolTip.Tag = null;
            this.ToolTip.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.ToolTip.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ToolTip.TextMargin = 2;
            this.ToolTip.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.ToolTip.TitleForeColor = System.Drawing.Color.Black;
            this.ToolTip.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.ToolTip.ToolTipTitle = "";
            // 
            // LoginForm
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.MainPanel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "LoginForm";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.LoginForm_FormClosing);
            this.Load += new System.EventHandler(this.LoginForm_Load);
            this.MainPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.LogoBox)).EndInit();
            this.ErrorPanel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse Elipse;
        private Bunifu.UI.WinForms.BunifuFormDock FormDock;
        private Bunifu.UI.WinForms.BunifuGradientPanel MainPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton UserButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton WorkerButton;
        private Bunifu.UI.WinForms.BunifuTextBox UserNameTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox PasswordTextBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LoginButton;
        private Bunifu.UI.WinForms.BunifuTextBox ErrorTextBox;
        private System.Windows.Forms.Panel ErrorPanel;
        private Bunifu.Framework.UI.BunifuThinButton2 ForgotPasswordThinButton;
        private Bunifu.Framework.UI.BunifuThinButton2 SignUpThinButton;
        private System.Windows.Forms.Button ExitButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton RusButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton EngButton;
        private System.Windows.Forms.PictureBox LogoBox;
        private Bunifu.UI.WinForms.BunifuToolTip ToolTip;
    }
}