
namespace WareHouse.Forms
{
    partial class OrderView
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(OrderView));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.UserNameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.OrderIDTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ProductsPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.OrderStatusTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ShapeButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Separator = new System.Windows.Forms.Panel();
            this.ProcessButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PayButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ShipButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ExecuteButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CreateReportButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.OrderTimeTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ToolTip = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.SuspendLayout();
            // 
            // UserNameTextBox
            // 
            this.UserNameTextBox.AcceptsReturn = false;
            this.UserNameTextBox.AcceptsTab = false;
            this.UserNameTextBox.AnimationSpeed = 200;
            this.UserNameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.UserNameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.UserNameTextBox.BackColor = System.Drawing.Color.Transparent;
            this.UserNameTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UserNameTextBox.BackgroundImage")));
            this.UserNameTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.UserNameTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UserNameTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UserNameTextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.UserNameTextBox.BorderRadius = 25;
            this.UserNameTextBox.BorderThickness = 1;
            this.UserNameTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.UserNameTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.UserNameTextBox.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.UserNameTextBox.DefaultText = "";
            this.UserNameTextBox.FillColor = System.Drawing.Color.White;
            this.UserNameTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.UserNameTextBox.HideSelection = true;
            this.UserNameTextBox.IconLeft = global::WareHouse.Properties.Resources.user;
            this.UserNameTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.UserNameTextBox.IconPadding = 10;
            this.UserNameTextBox.IconRight = null;
            this.UserNameTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.UserNameTextBox.Lines = new string[0];
            this.UserNameTextBox.Location = new System.Drawing.Point(3, 3);
            this.UserNameTextBox.MaxLength = 32767;
            this.UserNameTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.UserNameTextBox.Modified = false;
            this.UserNameTextBox.Multiline = false;
            this.UserNameTextBox.Name = "UserNameTextBox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UserNameTextBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.UserNameTextBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UserNameTextBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UserNameTextBox.OnIdleState = stateProperties4;
            this.UserNameTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.UserNameTextBox.PasswordChar = '\0';
            this.UserNameTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.UserNameTextBox.PlaceholderText = "Login / e-mail";
            this.UserNameTextBox.ReadOnly = true;
            this.UserNameTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.UserNameTextBox.SelectedText = "";
            this.UserNameTextBox.SelectionLength = 0;
            this.UserNameTextBox.SelectionStart = 0;
            this.UserNameTextBox.ShortcutsEnabled = true;
            this.UserNameTextBox.Size = new System.Drawing.Size(300, 40);
            this.UserNameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.UserNameTextBox.TabIndex = 38;
            this.UserNameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.UserNameTextBox.TextMarginBottom = 0;
            this.UserNameTextBox.TextMarginLeft = 10;
            this.UserNameTextBox.TextMarginTop = 0;
            this.UserNameTextBox.TextPlaceholder = "Login / e-mail";
            this.ToolTip.SetToolTip(this.UserNameTextBox, "User Login / e-mail");
            this.ToolTip.SetToolTipIcon(this.UserNameTextBox, global::WareHouse.Properties.Resources.message);
            this.ToolTip.SetToolTipTitle(this.UserNameTextBox, "Login");
            this.UserNameTextBox.UseSystemPasswordChar = false;
            this.UserNameTextBox.WordWrap = true;
            // 
            // OrderIDTextBox
            // 
            this.OrderIDTextBox.AcceptsReturn = false;
            this.OrderIDTextBox.AcceptsTab = false;
            this.OrderIDTextBox.AnimationSpeed = 200;
            this.OrderIDTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.OrderIDTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.OrderIDTextBox.BackColor = System.Drawing.Color.Transparent;
            this.OrderIDTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("OrderIDTextBox.BackgroundImage")));
            this.OrderIDTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.OrderIDTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.OrderIDTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.OrderIDTextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.OrderIDTextBox.BorderRadius = 25;
            this.OrderIDTextBox.BorderThickness = 1;
            this.OrderIDTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.OrderIDTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderIDTextBox.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.OrderIDTextBox.DefaultText = "";
            this.OrderIDTextBox.FillColor = System.Drawing.Color.White;
            this.OrderIDTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.OrderIDTextBox.HideSelection = true;
            this.OrderIDTextBox.IconLeft = global::WareHouse.Properties.Resources.order_Id;
            this.OrderIDTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderIDTextBox.IconPadding = 10;
            this.OrderIDTextBox.IconRight = null;
            this.OrderIDTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderIDTextBox.Lines = new string[0];
            this.OrderIDTextBox.Location = new System.Drawing.Point(497, 3);
            this.OrderIDTextBox.MaxLength = 32767;
            this.OrderIDTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.OrderIDTextBox.Modified = false;
            this.OrderIDTextBox.Multiline = false;
            this.OrderIDTextBox.Name = "OrderIDTextBox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderIDTextBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.OrderIDTextBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderIDTextBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderIDTextBox.OnIdleState = stateProperties8;
            this.OrderIDTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.OrderIDTextBox.PasswordChar = '\0';
            this.OrderIDTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.OrderIDTextBox.PlaceholderText = "Order Id";
            this.OrderIDTextBox.ReadOnly = true;
            this.OrderIDTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.OrderIDTextBox.SelectedText = "";
            this.OrderIDTextBox.SelectionLength = 0;
            this.OrderIDTextBox.SelectionStart = 0;
            this.OrderIDTextBox.ShortcutsEnabled = true;
            this.OrderIDTextBox.Size = new System.Drawing.Size(300, 40);
            this.OrderIDTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.OrderIDTextBox.TabIndex = 39;
            this.OrderIDTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.OrderIDTextBox.TextMarginBottom = 0;
            this.OrderIDTextBox.TextMarginLeft = 10;
            this.OrderIDTextBox.TextMarginTop = 0;
            this.OrderIDTextBox.TextPlaceholder = "Order Id";
            this.ToolTip.SetToolTip(this.OrderIDTextBox, "Order ID");
            this.ToolTip.SetToolTipIcon(this.OrderIDTextBox, global::WareHouse.Properties.Resources.message);
            this.ToolTip.SetToolTipTitle(this.OrderIDTextBox, "ID");
            this.OrderIDTextBox.UseSystemPasswordChar = false;
            this.OrderIDTextBox.WordWrap = true;
            // 
            // ProductsPanel
            // 
            this.ProductsPanel.AutoScroll = true;
            this.ProductsPanel.Location = new System.Drawing.Point(3, 49);
            this.ProductsPanel.Name = "ProductsPanel";
            this.ProductsPanel.Size = new System.Drawing.Size(794, 241);
            this.ProductsPanel.TabIndex = 40;
            this.ToolTip.SetToolTip(this.ProductsPanel, "");
            this.ToolTip.SetToolTipIcon(this.ProductsPanel, null);
            this.ToolTip.SetToolTipTitle(this.ProductsPanel, "");
            // 
            // OrderStatusTextBox
            // 
            this.OrderStatusTextBox.AcceptsReturn = false;
            this.OrderStatusTextBox.AcceptsTab = false;
            this.OrderStatusTextBox.AnimationSpeed = 200;
            this.OrderStatusTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.OrderStatusTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.OrderStatusTextBox.BackColor = System.Drawing.Color.Transparent;
            this.OrderStatusTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("OrderStatusTextBox.BackgroundImage")));
            this.OrderStatusTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.OrderStatusTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.OrderStatusTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.OrderStatusTextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.OrderStatusTextBox.BorderRadius = 25;
            this.OrderStatusTextBox.BorderThickness = 1;
            this.OrderStatusTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.OrderStatusTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderStatusTextBox.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.OrderStatusTextBox.DefaultText = "";
            this.OrderStatusTextBox.FillColor = System.Drawing.Color.White;
            this.OrderStatusTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.OrderStatusTextBox.HideSelection = true;
            this.OrderStatusTextBox.IconLeft = global::WareHouse.Properties.Resources.order_status_2;
            this.OrderStatusTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderStatusTextBox.IconPadding = 10;
            this.OrderStatusTextBox.IconRight = null;
            this.OrderStatusTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderStatusTextBox.Lines = new string[0];
            this.OrderStatusTextBox.Location = new System.Drawing.Point(3, 298);
            this.OrderStatusTextBox.MaxLength = 32767;
            this.OrderStatusTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.OrderStatusTextBox.Modified = false;
            this.OrderStatusTextBox.Multiline = false;
            this.OrderStatusTextBox.Name = "OrderStatusTextBox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderStatusTextBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.OrderStatusTextBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderStatusTextBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderStatusTextBox.OnIdleState = stateProperties12;
            this.OrderStatusTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.OrderStatusTextBox.PasswordChar = '\0';
            this.OrderStatusTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.OrderStatusTextBox.PlaceholderText = "Order Status";
            this.OrderStatusTextBox.ReadOnly = true;
            this.OrderStatusTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.OrderStatusTextBox.SelectedText = "";
            this.OrderStatusTextBox.SelectionLength = 0;
            this.OrderStatusTextBox.SelectionStart = 0;
            this.OrderStatusTextBox.ShortcutsEnabled = true;
            this.OrderStatusTextBox.Size = new System.Drawing.Size(300, 40);
            this.OrderStatusTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.OrderStatusTextBox.TabIndex = 41;
            this.OrderStatusTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.OrderStatusTextBox.TextMarginBottom = 0;
            this.OrderStatusTextBox.TextMarginLeft = 10;
            this.OrderStatusTextBox.TextMarginTop = 0;
            this.OrderStatusTextBox.TextPlaceholder = "Order Status";
            this.ToolTip.SetToolTip(this.OrderStatusTextBox, "Current Order Status");
            this.ToolTip.SetToolTipIcon(this.OrderStatusTextBox, global::WareHouse.Properties.Resources.message);
            this.ToolTip.SetToolTipTitle(this.OrderStatusTextBox, "Status");
            this.OrderStatusTextBox.UseSystemPasswordChar = false;
            this.OrderStatusTextBox.WordWrap = true;
            // 
            // ShapeButton
            // 
            this.ShapeButton.AllowAnimations = true;
            this.ShapeButton.AllowMouseEffects = true;
            this.ShapeButton.AllowToggling = false;
            this.ShapeButton.AnimationSpeed = 200;
            this.ShapeButton.AutoGenerateColors = false;
            this.ShapeButton.AutoRoundBorders = false;
            this.ShapeButton.AutoSizeLeftIcon = true;
            this.ShapeButton.AutoSizeRightIcon = true;
            this.ShapeButton.BackColor = System.Drawing.Color.Transparent;
            this.ShapeButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ShapeButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ShapeButton.BackgroundImage")));
            this.ShapeButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShapeButton.ButtonText = "Shape";
            this.ShapeButton.ButtonTextMarginLeft = 0;
            this.ShapeButton.ColorContrastOnClick = 45;
            this.ShapeButton.ColorContrastOnHover = 45;
            this.ShapeButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ShapeButton.CustomizableEdges = borderEdges1;
            this.ShapeButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ShapeButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ShapeButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ShapeButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ShapeButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ShapeButton.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.ShapeButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ShapeButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ShapeButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ShapeButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ShapeButton.IconMarginLeft = 11;
            this.ShapeButton.IconPadding = 10;
            this.ShapeButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ShapeButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ShapeButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ShapeButton.IconSize = 25;
            this.ShapeButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ShapeButton.IdleBorderRadius = 30;
            this.ShapeButton.IdleBorderThickness = 2;
            this.ShapeButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ShapeButton.IdleIconLeftImage = null;
            this.ShapeButton.IdleIconRightImage = null;
            this.ShapeButton.IndicateFocus = false;
            this.ShapeButton.Location = new System.Drawing.Point(624, 298);
            this.ShapeButton.Name = "ShapeButton";
            this.ShapeButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ShapeButton.OnDisabledState.BorderRadius = 30;
            this.ShapeButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShapeButton.OnDisabledState.BorderThickness = 2;
            this.ShapeButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ShapeButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ShapeButton.OnDisabledState.IconLeftImage = null;
            this.ShapeButton.OnDisabledState.IconRightImage = null;
            this.ShapeButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShapeButton.onHoverState.BorderRadius = 30;
            this.ShapeButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShapeButton.onHoverState.BorderThickness = 2;
            this.ShapeButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShapeButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ShapeButton.onHoverState.IconLeftImage = null;
            this.ShapeButton.onHoverState.IconRightImage = null;
            this.ShapeButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ShapeButton.OnIdleState.BorderRadius = 30;
            this.ShapeButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShapeButton.OnIdleState.BorderThickness = 2;
            this.ShapeButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ShapeButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ShapeButton.OnIdleState.IconLeftImage = null;
            this.ShapeButton.OnIdleState.IconRightImage = null;
            this.ShapeButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ShapeButton.OnPressedState.BorderRadius = 30;
            this.ShapeButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShapeButton.OnPressedState.BorderThickness = 2;
            this.ShapeButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ShapeButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ShapeButton.OnPressedState.IconLeftImage = null;
            this.ShapeButton.OnPressedState.IconRightImage = null;
            this.ShapeButton.Size = new System.Drawing.Size(173, 40);
            this.ShapeButton.TabIndex = 50;
            this.ShapeButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ShapeButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ShapeButton.TextMarginLeft = 0;
            this.ShapeButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.ShapeButton, "");
            this.ToolTip.SetToolTipIcon(this.ShapeButton, null);
            this.ToolTip.SetToolTipTitle(this.ShapeButton, "");
            this.ShapeButton.UseDefaultRadiusAndThickness = true;
            this.ShapeButton.Click += new System.EventHandler(this.ShapeButton_Click);
            // 
            // Separator
            // 
            this.Separator.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(214)))), ((int)(((byte)(224)))));
            this.Separator.Location = new System.Drawing.Point(3, 349);
            this.Separator.Name = "Separator";
            this.Separator.Size = new System.Drawing.Size(794, 5);
            this.Separator.TabIndex = 51;
            this.ToolTip.SetToolTip(this.Separator, "");
            this.ToolTip.SetToolTipIcon(this.Separator, null);
            this.ToolTip.SetToolTipTitle(this.Separator, "");
            // 
            // ProcessButton
            // 
            this.ProcessButton.AllowAnimations = true;
            this.ProcessButton.AllowMouseEffects = true;
            this.ProcessButton.AllowToggling = false;
            this.ProcessButton.AnimationSpeed = 200;
            this.ProcessButton.AutoGenerateColors = false;
            this.ProcessButton.AutoRoundBorders = false;
            this.ProcessButton.AutoSizeLeftIcon = true;
            this.ProcessButton.AutoSizeRightIcon = true;
            this.ProcessButton.BackColor = System.Drawing.Color.Transparent;
            this.ProcessButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ProcessButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProcessButton.BackgroundImage")));
            this.ProcessButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProcessButton.ButtonText = "Process";
            this.ProcessButton.ButtonTextMarginLeft = 0;
            this.ProcessButton.ColorContrastOnClick = 45;
            this.ProcessButton.ColorContrastOnHover = 45;
            this.ProcessButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.ProcessButton.CustomizableEdges = borderEdges2;
            this.ProcessButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ProcessButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ProcessButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProcessButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ProcessButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ProcessButton.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.ProcessButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ProcessButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ProcessButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ProcessButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ProcessButton.IconMarginLeft = 11;
            this.ProcessButton.IconPadding = 10;
            this.ProcessButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ProcessButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ProcessButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ProcessButton.IconSize = 25;
            this.ProcessButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ProcessButton.IdleBorderRadius = 30;
            this.ProcessButton.IdleBorderThickness = 2;
            this.ProcessButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ProcessButton.IdleIconLeftImage = null;
            this.ProcessButton.IdleIconRightImage = null;
            this.ProcessButton.IndicateFocus = false;
            this.ProcessButton.Location = new System.Drawing.Point(624, 298);
            this.ProcessButton.Name = "ProcessButton";
            this.ProcessButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ProcessButton.OnDisabledState.BorderRadius = 30;
            this.ProcessButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProcessButton.OnDisabledState.BorderThickness = 2;
            this.ProcessButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProcessButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ProcessButton.OnDisabledState.IconLeftImage = null;
            this.ProcessButton.OnDisabledState.IconRightImage = null;
            this.ProcessButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProcessButton.onHoverState.BorderRadius = 30;
            this.ProcessButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProcessButton.onHoverState.BorderThickness = 2;
            this.ProcessButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProcessButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ProcessButton.onHoverState.IconLeftImage = null;
            this.ProcessButton.onHoverState.IconRightImage = null;
            this.ProcessButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ProcessButton.OnIdleState.BorderRadius = 30;
            this.ProcessButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProcessButton.OnIdleState.BorderThickness = 2;
            this.ProcessButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ProcessButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ProcessButton.OnIdleState.IconLeftImage = null;
            this.ProcessButton.OnIdleState.IconRightImage = null;
            this.ProcessButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ProcessButton.OnPressedState.BorderRadius = 30;
            this.ProcessButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ProcessButton.OnPressedState.BorderThickness = 2;
            this.ProcessButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ProcessButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ProcessButton.OnPressedState.IconLeftImage = null;
            this.ProcessButton.OnPressedState.IconRightImage = null;
            this.ProcessButton.Size = new System.Drawing.Size(173, 40);
            this.ProcessButton.TabIndex = 52;
            this.ProcessButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ProcessButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ProcessButton.TextMarginLeft = 0;
            this.ProcessButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.ProcessButton, "");
            this.ToolTip.SetToolTipIcon(this.ProcessButton, null);
            this.ToolTip.SetToolTipTitle(this.ProcessButton, "");
            this.ProcessButton.UseDefaultRadiusAndThickness = true;
            this.ProcessButton.Click += new System.EventHandler(this.ProcessButton_Click);
            // 
            // PayButton
            // 
            this.PayButton.AllowAnimations = true;
            this.PayButton.AllowMouseEffects = true;
            this.PayButton.AllowToggling = false;
            this.PayButton.AnimationSpeed = 200;
            this.PayButton.AutoGenerateColors = false;
            this.PayButton.AutoRoundBorders = false;
            this.PayButton.AutoSizeLeftIcon = true;
            this.PayButton.AutoSizeRightIcon = true;
            this.PayButton.BackColor = System.Drawing.Color.Transparent;
            this.PayButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.PayButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PayButton.BackgroundImage")));
            this.PayButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PayButton.ButtonText = "Pay";
            this.PayButton.ButtonTextMarginLeft = 0;
            this.PayButton.ColorContrastOnClick = 45;
            this.PayButton.ColorContrastOnHover = 45;
            this.PayButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.PayButton.CustomizableEdges = borderEdges3;
            this.PayButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.PayButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PayButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PayButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PayButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.PayButton.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.PayButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.PayButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.PayButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.PayButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.PayButton.IconMarginLeft = 11;
            this.PayButton.IconPadding = 10;
            this.PayButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.PayButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PayButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.PayButton.IconSize = 25;
            this.PayButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.PayButton.IdleBorderRadius = 30;
            this.PayButton.IdleBorderThickness = 2;
            this.PayButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.PayButton.IdleIconLeftImage = null;
            this.PayButton.IdleIconRightImage = null;
            this.PayButton.IndicateFocus = false;
            this.PayButton.Location = new System.Drawing.Point(624, 298);
            this.PayButton.Name = "PayButton";
            this.PayButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PayButton.OnDisabledState.BorderRadius = 30;
            this.PayButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PayButton.OnDisabledState.BorderThickness = 2;
            this.PayButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PayButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PayButton.OnDisabledState.IconLeftImage = null;
            this.PayButton.OnDisabledState.IconRightImage = null;
            this.PayButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PayButton.onHoverState.BorderRadius = 30;
            this.PayButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PayButton.onHoverState.BorderThickness = 2;
            this.PayButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PayButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.PayButton.onHoverState.IconLeftImage = null;
            this.PayButton.onHoverState.IconRightImage = null;
            this.PayButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.PayButton.OnIdleState.BorderRadius = 30;
            this.PayButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PayButton.OnIdleState.BorderThickness = 2;
            this.PayButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.PayButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.PayButton.OnIdleState.IconLeftImage = null;
            this.PayButton.OnIdleState.IconRightImage = null;
            this.PayButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PayButton.OnPressedState.BorderRadius = 30;
            this.PayButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PayButton.OnPressedState.BorderThickness = 2;
            this.PayButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PayButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.PayButton.OnPressedState.IconLeftImage = null;
            this.PayButton.OnPressedState.IconRightImage = null;
            this.PayButton.Size = new System.Drawing.Size(173, 40);
            this.PayButton.TabIndex = 53;
            this.PayButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.PayButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.PayButton.TextMarginLeft = 0;
            this.PayButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.PayButton, "");
            this.ToolTip.SetToolTipIcon(this.PayButton, null);
            this.ToolTip.SetToolTipTitle(this.PayButton, "");
            this.PayButton.UseDefaultRadiusAndThickness = true;
            this.PayButton.Click += new System.EventHandler(this.PayButton_Click);
            // 
            // ShipButton
            // 
            this.ShipButton.AllowAnimations = true;
            this.ShipButton.AllowMouseEffects = true;
            this.ShipButton.AllowToggling = false;
            this.ShipButton.AnimationSpeed = 200;
            this.ShipButton.AutoGenerateColors = false;
            this.ShipButton.AutoRoundBorders = false;
            this.ShipButton.AutoSizeLeftIcon = true;
            this.ShipButton.AutoSizeRightIcon = true;
            this.ShipButton.BackColor = System.Drawing.Color.Transparent;
            this.ShipButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ShipButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ShipButton.BackgroundImage")));
            this.ShipButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShipButton.ButtonText = "Ship";
            this.ShipButton.ButtonTextMarginLeft = 0;
            this.ShipButton.ColorContrastOnClick = 45;
            this.ShipButton.ColorContrastOnHover = 45;
            this.ShipButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.ShipButton.CustomizableEdges = borderEdges4;
            this.ShipButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ShipButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ShipButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ShipButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ShipButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ShipButton.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.ShipButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ShipButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ShipButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ShipButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ShipButton.IconMarginLeft = 11;
            this.ShipButton.IconPadding = 10;
            this.ShipButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ShipButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ShipButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ShipButton.IconSize = 25;
            this.ShipButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ShipButton.IdleBorderRadius = 30;
            this.ShipButton.IdleBorderThickness = 2;
            this.ShipButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ShipButton.IdleIconLeftImage = null;
            this.ShipButton.IdleIconRightImage = null;
            this.ShipButton.IndicateFocus = false;
            this.ShipButton.Location = new System.Drawing.Point(624, 298);
            this.ShipButton.Name = "ShipButton";
            this.ShipButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ShipButton.OnDisabledState.BorderRadius = 30;
            this.ShipButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShipButton.OnDisabledState.BorderThickness = 2;
            this.ShipButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ShipButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ShipButton.OnDisabledState.IconLeftImage = null;
            this.ShipButton.OnDisabledState.IconRightImage = null;
            this.ShipButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShipButton.onHoverState.BorderRadius = 30;
            this.ShipButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShipButton.onHoverState.BorderThickness = 2;
            this.ShipButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShipButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ShipButton.onHoverState.IconLeftImage = null;
            this.ShipButton.onHoverState.IconRightImage = null;
            this.ShipButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ShipButton.OnIdleState.BorderRadius = 30;
            this.ShipButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShipButton.OnIdleState.BorderThickness = 2;
            this.ShipButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ShipButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ShipButton.OnIdleState.IconLeftImage = null;
            this.ShipButton.OnIdleState.IconRightImage = null;
            this.ShipButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ShipButton.OnPressedState.BorderRadius = 30;
            this.ShipButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ShipButton.OnPressedState.BorderThickness = 2;
            this.ShipButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ShipButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ShipButton.OnPressedState.IconLeftImage = null;
            this.ShipButton.OnPressedState.IconRightImage = null;
            this.ShipButton.Size = new System.Drawing.Size(173, 40);
            this.ShipButton.TabIndex = 54;
            this.ShipButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ShipButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ShipButton.TextMarginLeft = 0;
            this.ShipButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.ShipButton, "");
            this.ToolTip.SetToolTipIcon(this.ShipButton, null);
            this.ToolTip.SetToolTipTitle(this.ShipButton, "");
            this.ShipButton.UseDefaultRadiusAndThickness = true;
            this.ShipButton.Click += new System.EventHandler(this.ShipButton_Click);
            // 
            // ExecuteButton
            // 
            this.ExecuteButton.AllowAnimations = true;
            this.ExecuteButton.AllowMouseEffects = true;
            this.ExecuteButton.AllowToggling = false;
            this.ExecuteButton.AnimationSpeed = 200;
            this.ExecuteButton.AutoGenerateColors = false;
            this.ExecuteButton.AutoRoundBorders = false;
            this.ExecuteButton.AutoSizeLeftIcon = true;
            this.ExecuteButton.AutoSizeRightIcon = true;
            this.ExecuteButton.BackColor = System.Drawing.Color.Transparent;
            this.ExecuteButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ExecuteButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ExecuteButton.BackgroundImage")));
            this.ExecuteButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ExecuteButton.ButtonText = "Execute";
            this.ExecuteButton.ButtonTextMarginLeft = 0;
            this.ExecuteButton.ColorContrastOnClick = 45;
            this.ExecuteButton.ColorContrastOnHover = 45;
            this.ExecuteButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.ExecuteButton.CustomizableEdges = borderEdges5;
            this.ExecuteButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ExecuteButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ExecuteButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ExecuteButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ExecuteButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ExecuteButton.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.ExecuteButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ExecuteButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ExecuteButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ExecuteButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ExecuteButton.IconMarginLeft = 11;
            this.ExecuteButton.IconPadding = 10;
            this.ExecuteButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ExecuteButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ExecuteButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ExecuteButton.IconSize = 25;
            this.ExecuteButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ExecuteButton.IdleBorderRadius = 30;
            this.ExecuteButton.IdleBorderThickness = 2;
            this.ExecuteButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ExecuteButton.IdleIconLeftImage = null;
            this.ExecuteButton.IdleIconRightImage = null;
            this.ExecuteButton.IndicateFocus = false;
            this.ExecuteButton.Location = new System.Drawing.Point(624, 298);
            this.ExecuteButton.Name = "ExecuteButton";
            this.ExecuteButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ExecuteButton.OnDisabledState.BorderRadius = 30;
            this.ExecuteButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ExecuteButton.OnDisabledState.BorderThickness = 2;
            this.ExecuteButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ExecuteButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ExecuteButton.OnDisabledState.IconLeftImage = null;
            this.ExecuteButton.OnDisabledState.IconRightImage = null;
            this.ExecuteButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ExecuteButton.onHoverState.BorderRadius = 30;
            this.ExecuteButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ExecuteButton.onHoverState.BorderThickness = 2;
            this.ExecuteButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ExecuteButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ExecuteButton.onHoverState.IconLeftImage = null;
            this.ExecuteButton.onHoverState.IconRightImage = null;
            this.ExecuteButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.ExecuteButton.OnIdleState.BorderRadius = 30;
            this.ExecuteButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ExecuteButton.OnIdleState.BorderThickness = 2;
            this.ExecuteButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.ExecuteButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.ExecuteButton.OnIdleState.IconLeftImage = null;
            this.ExecuteButton.OnIdleState.IconRightImage = null;
            this.ExecuteButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ExecuteButton.OnPressedState.BorderRadius = 30;
            this.ExecuteButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ExecuteButton.OnPressedState.BorderThickness = 2;
            this.ExecuteButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ExecuteButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ExecuteButton.OnPressedState.IconLeftImage = null;
            this.ExecuteButton.OnPressedState.IconRightImage = null;
            this.ExecuteButton.Size = new System.Drawing.Size(173, 40);
            this.ExecuteButton.TabIndex = 55;
            this.ExecuteButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ExecuteButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ExecuteButton.TextMarginLeft = 0;
            this.ExecuteButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.ExecuteButton, "");
            this.ToolTip.SetToolTipIcon(this.ExecuteButton, null);
            this.ToolTip.SetToolTipTitle(this.ExecuteButton, "");
            this.ExecuteButton.UseDefaultRadiusAndThickness = true;
            this.ExecuteButton.Click += new System.EventHandler(this.ExecuteButton_Click);
            // 
            // CreateReportButton
            // 
            this.CreateReportButton.AllowAnimations = true;
            this.CreateReportButton.AllowMouseEffects = true;
            this.CreateReportButton.AllowToggling = false;
            this.CreateReportButton.AnimationSpeed = 200;
            this.CreateReportButton.AutoGenerateColors = false;
            this.CreateReportButton.AutoRoundBorders = false;
            this.CreateReportButton.AutoSizeLeftIcon = true;
            this.CreateReportButton.AutoSizeRightIcon = true;
            this.CreateReportButton.BackColor = System.Drawing.Color.Transparent;
            this.CreateReportButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.CreateReportButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CreateReportButton.BackgroundImage")));
            this.CreateReportButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateReportButton.ButtonText = "Report";
            this.CreateReportButton.ButtonTextMarginLeft = 0;
            this.CreateReportButton.ColorContrastOnClick = 45;
            this.CreateReportButton.ColorContrastOnHover = 45;
            this.CreateReportButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.CreateReportButton.CustomizableEdges = borderEdges6;
            this.CreateReportButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CreateReportButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CreateReportButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CreateReportButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CreateReportButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CreateReportButton.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.CreateReportButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.CreateReportButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CreateReportButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CreateReportButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CreateReportButton.IconMarginLeft = 11;
            this.CreateReportButton.IconPadding = 10;
            this.CreateReportButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CreateReportButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CreateReportButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CreateReportButton.IconSize = 25;
            this.CreateReportButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.CreateReportButton.IdleBorderRadius = 30;
            this.CreateReportButton.IdleBorderThickness = 2;
            this.CreateReportButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.CreateReportButton.IdleIconLeftImage = null;
            this.CreateReportButton.IdleIconRightImage = null;
            this.CreateReportButton.IndicateFocus = false;
            this.CreateReportButton.Location = new System.Drawing.Point(309, 3);
            this.CreateReportButton.Name = "CreateReportButton";
            this.CreateReportButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CreateReportButton.OnDisabledState.BorderRadius = 30;
            this.CreateReportButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateReportButton.OnDisabledState.BorderThickness = 2;
            this.CreateReportButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CreateReportButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CreateReportButton.OnDisabledState.IconLeftImage = null;
            this.CreateReportButton.OnDisabledState.IconRightImage = null;
            this.CreateReportButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CreateReportButton.onHoverState.BorderRadius = 30;
            this.CreateReportButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateReportButton.onHoverState.BorderThickness = 2;
            this.CreateReportButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CreateReportButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.CreateReportButton.onHoverState.IconLeftImage = null;
            this.CreateReportButton.onHoverState.IconRightImage = null;
            this.CreateReportButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(152)))), ((int)(((byte)(218)))));
            this.CreateReportButton.OnIdleState.BorderRadius = 30;
            this.CreateReportButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateReportButton.OnIdleState.BorderThickness = 2;
            this.CreateReportButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(69)))), ((int)(((byte)(170)))), ((int)(((byte)(242)))));
            this.CreateReportButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(250)))));
            this.CreateReportButton.OnIdleState.IconLeftImage = null;
            this.CreateReportButton.OnIdleState.IconRightImage = null;
            this.CreateReportButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CreateReportButton.OnPressedState.BorderRadius = 30;
            this.CreateReportButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateReportButton.OnPressedState.BorderThickness = 2;
            this.CreateReportButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CreateReportButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.CreateReportButton.OnPressedState.IconLeftImage = null;
            this.CreateReportButton.OnPressedState.IconRightImage = null;
            this.CreateReportButton.Size = new System.Drawing.Size(126, 40);
            this.CreateReportButton.TabIndex = 59;
            this.CreateReportButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CreateReportButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CreateReportButton.TextMarginLeft = 0;
            this.CreateReportButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTip.SetToolTip(this.CreateReportButton, "");
            this.ToolTip.SetToolTipIcon(this.CreateReportButton, null);
            this.ToolTip.SetToolTipTitle(this.CreateReportButton, "");
            this.CreateReportButton.UseDefaultRadiusAndThickness = true;
            this.CreateReportButton.Click += new System.EventHandler(this.CreateReportButton_Click);
            // 
            // OrderTimeTextBox
            // 
            this.OrderTimeTextBox.AcceptsReturn = false;
            this.OrderTimeTextBox.AcceptsTab = false;
            this.OrderTimeTextBox.AnimationSpeed = 200;
            this.OrderTimeTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.OrderTimeTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.OrderTimeTextBox.BackColor = System.Drawing.Color.Transparent;
            this.OrderTimeTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("OrderTimeTextBox.BackgroundImage")));
            this.OrderTimeTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.OrderTimeTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.OrderTimeTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.OrderTimeTextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.OrderTimeTextBox.BorderRadius = 25;
            this.OrderTimeTextBox.BorderThickness = 1;
            this.OrderTimeTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.OrderTimeTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderTimeTextBox.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.OrderTimeTextBox.DefaultText = "";
            this.OrderTimeTextBox.FillColor = System.Drawing.Color.White;
            this.OrderTimeTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.OrderTimeTextBox.HideSelection = true;
            this.OrderTimeTextBox.IconLeft = global::WareHouse.Properties.Resources.time;
            this.OrderTimeTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderTimeTextBox.IconPadding = 10;
            this.OrderTimeTextBox.IconRight = null;
            this.OrderTimeTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.OrderTimeTextBox.Lines = new string[0];
            this.OrderTimeTextBox.Location = new System.Drawing.Point(309, 298);
            this.OrderTimeTextBox.MaxLength = 32767;
            this.OrderTimeTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.OrderTimeTextBox.Modified = false;
            this.OrderTimeTextBox.Multiline = false;
            this.OrderTimeTextBox.Name = "OrderTimeTextBox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderTimeTextBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.OrderTimeTextBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderTimeTextBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.OrderTimeTextBox.OnIdleState = stateProperties16;
            this.OrderTimeTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.OrderTimeTextBox.PasswordChar = '\0';
            this.OrderTimeTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.OrderTimeTextBox.PlaceholderText = "Order Time";
            this.OrderTimeTextBox.ReadOnly = true;
            this.OrderTimeTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.OrderTimeTextBox.SelectedText = "";
            this.OrderTimeTextBox.SelectionLength = 0;
            this.OrderTimeTextBox.SelectionStart = 0;
            this.OrderTimeTextBox.ShortcutsEnabled = true;
            this.OrderTimeTextBox.Size = new System.Drawing.Size(300, 40);
            this.OrderTimeTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.OrderTimeTextBox.TabIndex = 60;
            this.OrderTimeTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.OrderTimeTextBox.TextMarginBottom = 0;
            this.OrderTimeTextBox.TextMarginLeft = 10;
            this.OrderTimeTextBox.TextMarginTop = 0;
            this.OrderTimeTextBox.TextPlaceholder = "Order Time";
            this.ToolTip.SetToolTip(this.OrderTimeTextBox, "Order Time Creation");
            this.ToolTip.SetToolTipIcon(this.OrderTimeTextBox, global::WareHouse.Properties.Resources.message);
            this.ToolTip.SetToolTipTitle(this.OrderTimeTextBox, "Time");
            this.OrderTimeTextBox.UseSystemPasswordChar = false;
            this.OrderTimeTextBox.WordWrap = true;
            // 
            // ToolTip
            // 
            this.ToolTip.Active = true;
            this.ToolTip.AlignTextWithTitle = false;
            this.ToolTip.AllowAutoClose = false;
            this.ToolTip.AllowFading = true;
            this.ToolTip.AutoCloseDuration = 5000;
            this.ToolTip.BackColor = System.Drawing.SystemColors.Control;
            this.ToolTip.BorderColor = System.Drawing.Color.Gainsboro;
            this.ToolTip.ClickToShowDisplayControl = false;
            this.ToolTip.ConvertNewlinesToBreakTags = true;
            this.ToolTip.DisplayControl = null;
            this.ToolTip.EntryAnimationSpeed = 350;
            this.ToolTip.ExitAnimationSpeed = 200;
            this.ToolTip.GenerateAutoCloseDuration = false;
            this.ToolTip.IconMargin = 6;
            this.ToolTip.InitialDelay = 0;
            this.ToolTip.Name = "ToolTip";
            this.ToolTip.Opacity = 1D;
            this.ToolTip.OverrideToolTipTitles = false;
            this.ToolTip.Padding = new System.Windows.Forms.Padding(10);
            this.ToolTip.ReshowDelay = 100;
            this.ToolTip.ShowAlways = true;
            this.ToolTip.ShowBorders = false;
            this.ToolTip.ShowIcons = true;
            this.ToolTip.ShowShadows = true;
            this.ToolTip.Tag = null;
            this.ToolTip.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.ToolTip.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ToolTip.TextMargin = 2;
            this.ToolTip.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.ToolTip.TitleForeColor = System.Drawing.Color.Black;
            this.ToolTip.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.ToolTip.ToolTipTitle = "";
            // 
            // OrderView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.Controls.Add(this.OrderTimeTextBox);
            this.Controls.Add(this.CreateReportButton);
            this.Controls.Add(this.ExecuteButton);
            this.Controls.Add(this.ShipButton);
            this.Controls.Add(this.PayButton);
            this.Controls.Add(this.ProcessButton);
            this.Controls.Add(this.Separator);
            this.Controls.Add(this.ShapeButton);
            this.Controls.Add(this.OrderStatusTextBox);
            this.Controls.Add(this.ProductsPanel);
            this.Controls.Add(this.OrderIDTextBox);
            this.Controls.Add(this.UserNameTextBox);
            this.MaximumSize = new System.Drawing.Size(800, 365);
            this.MinimumSize = new System.Drawing.Size(800, 365);
            this.Name = "OrderView";
            this.Size = new System.Drawing.Size(800, 365);
            this.ToolTip.SetToolTip(this, "");
            this.ToolTip.SetToolTipIcon(this, null);
            this.ToolTip.SetToolTipTitle(this, "");
            this.Load += new System.EventHandler(this.OrderView_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox UserNameTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox OrderIDTextBox;
        private System.Windows.Forms.FlowLayoutPanel ProductsPanel;
        private Bunifu.UI.WinForms.BunifuTextBox OrderStatusTextBox;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton ShapeButton;
        private System.Windows.Forms.Panel Separator;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton ProcessButton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton PayButton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton ShipButton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton ExecuteButton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton CreateReportButton;
        private Bunifu.UI.WinForms.BunifuTextBox OrderTimeTextBox;
        private Bunifu.UI.WinForms.BunifuToolTip ToolTip;
    }
}
