//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WareHouse.AppResources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Settings.
        /// </summary>
        internal static string AdditionalSettingsText {
            get {
                return ResourceManager.GetString("AdditionalSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string AddProductText {
            get {
                return ResourceManager.GetString("AddProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add root.
        /// </summary>
        internal static string AddRootText {
            get {
                return ResourceManager.GetString("AddRootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string AddSectionText {
            get {
                return ResourceManager.GetString("AddSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect address (only latin and cyrillic letters, digits and &quot;-&quot;).
        /// </summary>
        internal static string AdressCompanyException {
            get {
                return ResourceManager.GetString("AdressCompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ChangeImgText {
            get {
                return ResourceManager.GetString("ChangeImgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect chief name (only latin and cyrillic letters and &quot;-&quot;)..
        /// </summary>
        internal static string ChiefCompanyException {
            get {
                return ResourceManager.GetString("ChiefCompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect code (only latin letters, digits and &quot;-&quot;)..
        /// </summary>
        internal static string CodeProductException {
            get {
                return ResourceManager.GetString("CodeProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company address.
        /// </summary>
        internal static string CompanyAddressPlaceholder {
            get {
                return ResourceManager.GetString("CompanyAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter chief name.
        /// </summary>
        internal static string CompanyChiefPlaceholder {
            get {
                return ResourceManager.GetString("CompanyChiefPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company description.
        /// </summary>
        internal static string CompanyDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("CompanyDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company with the same name already exists..
        /// </summary>
        internal static string CompanyExistException {
            get {
                return ResourceManager.GetString("CompanyExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company name.
        /// </summary>
        internal static string CompanyNamePlaceholder {
            get {
                return ResourceManager.GetString("CompanyNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company with this name does not exist..
        /// </summary>
        internal static string CompanyNotFoundException {
            get {
                return ResourceManager.GetString("CompanyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company phone number.
        /// </summary>
        internal static string CompanyPhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("CompanyPhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No company selected / created..
        /// </summary>
        internal static string CompanySelectedException {
            get {
                return ResourceManager.GetString("CompanySelectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        internal static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount is not real number..
        /// </summary>
        internal static string DiscountParseException {
            get {
                return ResourceManager.GetString("DiscountParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect discount (only more than 0 and less than 100)..
        /// </summary>
        internal static string DiscountProductException {
            get {
                return ResourceManager.GetString("DiscountProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErorrMessage {
            get {
                return ResourceManager.GetString("ErorrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error!.
        /// </summary>
        internal static string FatalErrorMessage {
            get {
                return ResourceManager.GetString("FatalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string GeneralSettingsText {
            get {
                return ResourceManager.GetString("GeneralSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateButtonText {
            get {
                return ResourceManager.GetString("GenerateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png files (*.png)|*.png|jpg files (*.jpg)|*.jpg|bmp files (*.bmp)|*.bmp|All files (*.*)|*.*.
        /// </summary>
        internal static string ImageFileDialogFilter {
            get {
                return ResourceManager.GetString("ImageFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting image to base64..
        /// </summary>
        internal static string ImgToStringException {
            get {
                return ResourceManager.GetString("ImgToStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter minimum product quantity.
        /// </summary>
        internal static string MinimumQuantityPlaceholder {
            get {
                return ResourceManager.GetString("MinimumQuantityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name (only latin and cyrillic letters and &quot;-&quot;)..
        /// </summary>
        internal static string NameCompanyException {
            get {
                return ResourceManager.GetString("NameCompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name (only latin and cyrillic letters, digits)..
        /// </summary>
        internal static string NameProductException {
            get {
                return ResourceManager.GetString("NameProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name (only latin and cyrillic letters, digits)..
        /// </summary>
        internal static string NameSectionException {
            get {
                return ResourceManager.GetString("NameSectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect phone number (only digits and &quot;-&quot;)..
        /// </summary>
        internal static string PhoneNumberCompanyException {
            get {
                return ResourceManager.GetString("PhoneNumberCompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceButtonText {
            get {
                return ResourceManager.GetString("PriceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is not real number..
        /// </summary>
        internal static string PriceParseException {
            get {
                return ResourceManager.GetString("PriceParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect price..
        /// </summary>
        internal static string PriceProductException {
            get {
                return ResourceManager.GetString("PriceProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product code.
        /// </summary>
        internal static string ProductCodePlaceholder {
            get {
                return ResourceManager.GetString("ProductCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        internal static string ProductDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ProductDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product discount.
        /// </summary>
        internal static string ProductDiscountPlaceholder {
            get {
                return ResourceManager.GetString("ProductDiscountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with the same name in current section already exists..
        /// </summary>
        internal static string ProductExistException {
            get {
                return ResourceManager.GetString("ProductExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect quantity (more than 1)..
        /// </summary>
        internal static string ProductMinimumQuantityException {
            get {
                return ResourceManager.GetString("ProductMinimumQuantityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is not integer..
        /// </summary>
        internal static string ProductMinimumQuantityParseException {
            get {
                return ResourceManager.GetString("ProductMinimumQuantityParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product name.
        /// </summary>
        internal static string ProductNamePlaceholder {
            get {
                return ResourceManager.GetString("ProductNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with this name doesn&apos;t exist..
        /// </summary>
        internal static string ProductNotFoundException {
            get {
                return ResourceManager.GetString("ProductNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product price.
        /// </summary>
        internal static string ProductPricePlaceholder {
            get {
                return ResourceManager.GetString("ProductPricePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product quantity.
        /// </summary>
        internal static string ProductQuantityPlaceholder {
            get {
                return ResourceManager.GetString("ProductQuantityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product UCN.
        /// </summary>
        internal static string ProductUcnPlaceholder {
            get {
                return ResourceManager.GetString("ProductUcnPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string QuantityButtonText {
            get {
                return ResourceManager.GetString("QuantityButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is not integer..
        /// </summary>
        internal static string QuantityParseException {
            get {
                return ResourceManager.GetString("QuantityParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect quantity..
        /// </summary>
        internal static string QuantityProductException {
            get {
                return ResourceManager.GetString("QuantityProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter root name.
        /// </summary>
        internal static string RootNamePlaceholder {
            get {
                return ResourceManager.GetString("RootNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files(*.csv) | *.csv.
        /// </summary>
        internal static string SaveFileFilter {
            get {
                return ResourceManager.GetString("SaveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section with the same name in current root already exists..
        /// </summary>
        internal static string SectionExistException {
            get {
                return ResourceManager.GetString("SectionExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section with this name does not exist..
        /// </summary>
        internal static string SectionNotFoundException {
            get {
                return ResourceManager.GetString("SectionNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of these sections or tap cancel..
        /// </summary>
        internal static string SectionSelectException {
            get {
                return ResourceManager.GetString("SectionSelectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting image to base64..
        /// </summary>
        internal static string StringToImgException {
            get {
                return ResourceManager.GetString("StringToImgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect UCN (only latin letters, digits and &quot;-&quot;)..
        /// </summary>
        internal static string UcnProductException {
            get {
                return ResourceManager.GetString("UcnProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse already exist. Do you want rewrite?.
        /// </summary>
        internal static string WarehouseExistWarning {
            get {
                return ResourceManager.GetString("WarehouseExistWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string WarningMessageText {
            get {
                return ResourceManager.GetString("WarningMessageText", resourceCulture);
            }
        }
    }
}
