//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WareHouse.AppResources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Active Orders:.
        /// </summary>
        internal static string ActiveLabelText {
            get {
                return ResourceManager.GetString("ActiveLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Settings.
        /// </summary>
        internal static string AdditionalSettingsText {
            get {
                return ResourceManager.GetString("AdditionalSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string AddProductButtonToolTip {
            get {
                return ResourceManager.GetString("AddProductButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string AddProductButtonToolTipTitle {
            get {
                return ResourceManager.GetString("AddProductButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string AddProductText {
            get {
                return ResourceManager.GetString("AddProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Root.
        /// </summary>
        internal static string AddRootButtonToolTip {
            get {
                return ResourceManager.GetString("AddRootButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string AddRootButtonToolTipTitle {
            get {
                return ResourceManager.GetString("AddRootButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add root.
        /// </summary>
        internal static string AddRootText {
            get {
                return ResourceManager.GetString("AddRootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Section.
        /// </summary>
        internal static string AddSectionButtonToolTip {
            get {
                return ResourceManager.GetString("AddSectionButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string AddSectionButtonToolTipTitle {
            get {
                return ResourceManager.GetString("AddSectionButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string AddSectionText {
            get {
                return ResourceManager.GetString("AddSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect address (only latin and cyrillic letters, digits and &quot;-&quot;).
        /// </summary>
        internal static string AdressCompanyException {
            get {
                return ResourceManager.GetString("AdressCompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an instance running.
        /// </summary>
        internal static string ApplicationRunnigException {
            get {
                return ResourceManager.GetString("ApplicationRunnigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open basket cart.
        /// </summary>
        internal static string BasketBoxToolTip {
            get {
                return ResourceManager.GetString("BasketBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket cart.
        /// </summary>
        internal static string BasketBoxToolTipTitle {
            get {
                return ResourceManager.GetString("BasketBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Cart.
        /// </summary>
        internal static string BuyButtonText {
            get {
                return ResourceManager.GetString("BuyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        internal static string BuyButtonToolTip {
            get {
                return ResourceManager.GetString("BuyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string BuyButtonToolTipTitle {
            get {
                return ResourceManager.GetString("BuyButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account.
        /// </summary>
        internal static string ChangeAccBoxToolTip {
            get {
                return ResourceManager.GetString("ChangeAccBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string ChangeAccBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ChangeAccBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string ChangeButtonText_Completed {
            get {
                return ResourceManager.GetString("ChangeButtonText_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string ChangeButtonText_Execute {
            get {
                return ResourceManager.GetString("ChangeButtonText_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid up.
        /// </summary>
        internal static string ChangeButtonText_Paid_up {
            get {
                return ResourceManager.GetString("ChangeButtonText_Paid_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string ChangeButtonText_Pay {
            get {
                return ResourceManager.GetString("ChangeButtonText_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string ChangeButtonText_Process {
            get {
                return ResourceManager.GetString("ChangeButtonText_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        internal static string ChangeButtonText_Shape {
            get {
                return ResourceManager.GetString("ChangeButtonText_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        internal static string ChangeButtonText_Ship {
            get {
                return ResourceManager.GetString("ChangeButtonText_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ChangeImgText {
            get {
                return ResourceManager.GetString("ChangeImgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect chief name (only latin and cyrillic letters and &quot;-&quot;)..
        /// </summary>
        internal static string ChiefCompanyException {
            get {
                return ResourceManager.GetString("ChiefCompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chelyabinsk.
        /// </summary>
        internal static string CityChelyabinsk {
            get {
                return ResourceManager.GetString("CityChelyabinsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect city ID..
        /// </summary>
        internal static string CityIdException {
            get {
                return ResourceManager.GetString("CityIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazan.
        /// </summary>
        internal static string CityKazan {
            get {
                return ResourceManager.GetString("CityKazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krasnoyarsk.
        /// </summary>
        internal static string CityKrasnoyarsk {
            get {
                return ResourceManager.GetString("CityKrasnoyarsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moscow.
        /// </summary>
        internal static string CityMoscow {
            get {
                return ResourceManager.GetString("CityMoscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nizhny Novgorod.
        /// </summary>
        internal static string CityNizhnyNovgorod {
            get {
                return ResourceManager.GetString("CityNizhnyNovgorod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novosibirsk.
        /// </summary>
        internal static string CityNovosibirsk {
            get {
                return ResourceManager.GetString("CityNovosibirsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omsk.
        /// </summary>
        internal static string CityOmsk {
            get {
                return ResourceManager.GetString("CityOmsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permian.
        /// </summary>
        internal static string CityPermian {
            get {
                return ResourceManager.GetString("CityPermian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rostov-on-Don.
        /// </summary>
        internal static string CityRostovOnDon {
            get {
                return ResourceManager.GetString("CityRostovOnDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Petersburg.
        /// </summary>
        internal static string CitySaintPeter {
            get {
                return ResourceManager.GetString("CitySaintPeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samara.
        /// </summary>
        internal static string CitySamara {
            get {
                return ResourceManager.GetString("CitySamara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ufa.
        /// </summary>
        internal static string CityUfa {
            get {
                return ResourceManager.GetString("CityUfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgograd.
        /// </summary>
        internal static string CityVolgograd {
            get {
                return ResourceManager.GetString("CityVolgograd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voronezh.
        /// </summary>
        internal static string CityVoronezh {
            get {
                return ResourceManager.GetString("CityVoronezh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yekaterinburg.
        /// </summary>
        internal static string CityYekaterinburg {
            get {
                return ResourceManager.GetString("CityYekaterinburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect phone number..
        /// </summary>
        internal static string ClienPhoneNumberException {
            get {
                return ResourceManager.GetString("ClienPhoneNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user e-mail..
        /// </summary>
        internal static string ClientEmailException {
            get {
                return ResourceManager.GetString("ClientEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client with the same login or e-mail already exists..
        /// </summary>
        internal static string ClientExistException {
            get {
                return ResourceManager.GetString("ClientExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect first name..
        /// </summary>
        internal static string ClientFirstNameException {
            get {
                return ResourceManager.GetString("ClientFirstNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password..
        /// </summary>
        internal static string ClientGetException {
            get {
                return ResourceManager.GetString("ClientGetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect last name..
        /// </summary>
        internal static string ClientLastNameException {
            get {
                return ResourceManager.GetString("ClientLastNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username..
        /// </summary>
        internal static string ClientLoginNameException {
            get {
                return ResourceManager.GetString("ClientLoginNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s orders quantity.
        /// </summary>
        internal static string ClientOrdersQuantityTextBoxToolTip {
            get {
                return ResourceManager.GetString("ClientOrdersQuantityTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders quantity.
        /// </summary>
        internal static string ClientOrdersQuantityTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ClientOrdersQuantityTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password (minimum three characters, at least one letter, one number).
        /// </summary>
        internal static string ClientPasswordException {
            get {
                return ResourceManager.GetString("ClientPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect patronymic..
        /// </summary>
        internal static string ClientPatronymicException {
            get {
                return ResourceManager.GetString("ClientPatronymicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string ClientsButtonText {
            get {
                return ResourceManager.GetString("ClientsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect code (only latin letters, digits and &quot;-&quot;)..
        /// </summary>
        internal static string CodeProductException {
            get {
                return ResourceManager.GetString("CodeProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company address.
        /// </summary>
        internal static string CompanyAddressPlaceholder {
            get {
                return ResourceManager.GetString("CompanyAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter chief name.
        /// </summary>
        internal static string CompanyChiefPlaceholder {
            get {
                return ResourceManager.GetString("CompanyChiefPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company description.
        /// </summary>
        internal static string CompanyDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("CompanyDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company with the same name already exists..
        /// </summary>
        internal static string CompanyExistException {
            get {
                return ResourceManager.GetString("CompanyExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company name.
        /// </summary>
        internal static string CompanyNamePlaceholder {
            get {
                return ResourceManager.GetString("CompanyNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company with this name does not exist..
        /// </summary>
        internal static string CompanyNotFoundException {
            get {
                return ResourceManager.GetString("CompanyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company phone number.
        /// </summary>
        internal static string CompanyPhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("CompanyPhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No company selected / created..
        /// </summary>
        internal static string CompanySelectedException {
            get {
                return ResourceManager.GetString("CompanySelectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        internal static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create report.
        /// </summary>
        internal static string CreateReportButtonToolTip {
            get {
                return ResourceManager.GetString("CreateReportButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string CreateReportButtonToolTipTitle {
            get {
                return ResourceManager.GetString("CreateReportButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount is not real number..
        /// </summary>
        internal static string DiscountParseException {
            get {
                return ResourceManager.GetString("DiscountParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect discount (only more than 0 and less than 100)..
        /// </summary>
        internal static string DiscountProductException {
            get {
                return ResourceManager.GetString("DiscountProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language Into English.
        /// </summary>
        internal static string EngButtonToolTip {
            get {
                return ResourceManager.GetString("EngButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EngButtonToolTipTitle {
            get {
                return ResourceManager.GetString("EngButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErorrMessage {
            get {
                return ResourceManager.GetString("ErorrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CSV Report.
        /// </summary>
        internal static string ExportCsvButtonToolTip {
            get {
                return ResourceManager.GetString("ExportCsvButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string ExportCsvButtonToolTipTitle {
            get {
                return ResourceManager.GetString("ExportCsvButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error!.
        /// </summary>
        internal static string FatalErrorMessage {
            get {
                return ResourceManager.GetString("FatalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FirstNameTextBoxTextPlaceholder {
            get {
                return ResourceManager.GetString("FirstNameTextBoxTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPasswordThinButtonText {
            get {
                return ResourceManager.GetString("ForgotPasswordThinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string GeneralSettingsText {
            get {
                return ResourceManager.GetString("GeneralSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateButtonText {
            get {
                return ResourceManager.GetString("GenerateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Roots, Sections And Products.
        /// </summary>
        internal static string GenerateButtonToolTip {
            get {
                return ResourceManager.GetString("GenerateButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateButtonToolTipTitle {
            get {
                return ResourceManager.GetString("GenerateButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png files (*.png)|*.png|jpg files (*.jpg)|*.jpg|bmp files (*.bmp)|*.bmp|All files (*.*)|*.*.
        /// </summary>
        internal static string ImageFileDialogFilter {
            get {
                return ResourceManager.GetString("ImageFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting image to base64..
        /// </summary>
        internal static string ImgToStringException {
            get {
                return ResourceManager.GetString("ImgToStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastNameTextBoxTextPlaceholder {
            get {
                return ResourceManager.GetString("LastNameTextBoxTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data before upload.
        /// </summary>
        internal static string LoadWarningMessage {
            get {
                return ResourceManager.GetString("LoadWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string LoginLabelText {
            get {
                return ResourceManager.GetString("LoginLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string LoginTypeUser {
            get {
                return ResourceManager.GetString("LoginTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string LoginTypeWorker {
            get {
                return ResourceManager.GetString("LoginTypeWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string LogoLabel {
            get {
                return ResourceManager.GetString("LogoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter minimum product quantity.
        /// </summary>
        internal static string MinimumQuantityPlaceholder {
            get {
                return ResourceManager.GetString("MinimumQuantityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more info.
        /// </summary>
        internal static string MoreButtonToolTip {
            get {
                return ResourceManager.GetString("MoreButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string MoreButtonToolTipTitle {
            get {
                return ResourceManager.GetString("MoreButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name (only latin and cyrillic letters and &quot;-&quot;)..
        /// </summary>
        internal static string NameCompanyException {
            get {
                return ResourceManager.GetString("NameCompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name (only latin and cyrillic letters, digits)..
        /// </summary>
        internal static string NameProductException {
            get {
                return ResourceManager.GetString("NameProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name (only latin and cyrillic letters, digits)..
        /// </summary>
        internal static string NameSectionException {
            get {
                return ResourceManager.GetString("NameSectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not formed..
        /// </summary>
        internal static string OrderFormedException {
            get {
                return ResourceManager.GetString("OrderFormedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order unique ID.
        /// </summary>
        internal static string OrderIDTextBoxToolTip {
            get {
                return ResourceManager.GetString("OrderIDTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string OrderIDTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("OrderIDTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string OrderManageFormLogoLabelText {
            get {
                return ResourceManager.GetString("OrderManageFormLogoLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not paid up..
        /// </summary>
        internal static string OrderPaidUpException {
            get {
                return ResourceManager.GetString("OrderPaidUpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not processed..
        /// </summary>
        internal static string OrderProcessedException {
            get {
                return ResourceManager.GetString("OrderProcessedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect order quantity (more than 0)..
        /// </summary>
        internal static string OrderQuantityException {
            get {
                return ResourceManager.GetString("OrderQuantityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string OrderQuantityText {
            get {
                return ResourceManager.GetString("OrderQuantityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string OrdersButtonText {
            get {
                return ResourceManager.GetString("OrdersButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show user orders.
        /// </summary>
        internal static string OrdersButtonToolTip {
            get {
                return ResourceManager.GetString("OrdersButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string OrdersButtonToolTipTitle {
            get {
                return ResourceManager.GetString("OrdersButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not shipped..
        /// </summary>
        internal static string OrderShippedException {
            get {
                return ResourceManager.GetString("OrderShippedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current order status.
        /// </summary>
        internal static string OrderStatusTextBoxToolTip {
            get {
                return ResourceManager.GetString("OrderStatusTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string OrderStatusTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("OrderStatusTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order creation time.
        /// </summary>
        internal static string OrderTimeTextBoxToolTip {
            get {
                return ResourceManager.GetString("OrderTimeTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time creation.
        /// </summary>
        internal static string OrderTimeTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("OrderTimeTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordTextBoxTextPlaceholder {
            get {
                return ResourceManager.GetString("PasswordTextBoxTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        internal static string PatronymicTextBoxTextPlaceholder {
            get {
                return ResourceManager.GetString("PatronymicTextBoxTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect phone number (only digits and &quot;-&quot;)..
        /// </summary>
        internal static string PhoneNumberCompanyException {
            get {
                return ResourceManager.GetString("PhoneNumberCompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumberTextBoxTextPlaceholder {
            get {
                return ResourceManager.GetString("PhoneNumberTextBoxTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceButtonText {
            get {
                return ResourceManager.GetString("PriceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order section by product price.
        /// </summary>
        internal static string PriceButtonToolTip {
            get {
                return ResourceManager.GetString("PriceButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Order.
        /// </summary>
        internal static string PriceButtonToolTipTitle {
            get {
                return ResourceManager.GetString("PriceButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect minimum price..
        /// </summary>
        internal static string PriceMinimumException {
            get {
                return ResourceManager.GetString("PriceMinimumException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is not real number..
        /// </summary>
        internal static string PriceParseException {
            get {
                return ResourceManager.GetString("PriceParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect price..
        /// </summary>
        internal static string PriceProductException {
            get {
                return ResourceManager.GetString("PriceProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product code.
        /// </summary>
        internal static string ProductCodePlaceholder {
            get {
                return ResourceManager.GetString("ProductCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company: {0}.
        /// </summary>
        internal static string ProductCompanyText {
            get {
                return ResourceManager.GetString("ProductCompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product company.
        /// </summary>
        internal static string ProductCompanyTextBoxToolTip {
            get {
                return ResourceManager.GetString("ProductCompanyTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string ProductCompanyTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ProductCompanyTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string ProductControlMore {
            get {
                return ResourceManager.GetString("ProductControlMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: {0} {1}.
        /// </summary>
        internal static string ProductControlPrice {
            get {
                return ResourceManager.GetString("ProductControlPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: {0}.
        /// </summary>
        internal static string ProductControlTitle {
            get {
                return ResourceManager.GetString("ProductControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: {0}.
        /// </summary>
        internal static string ProductCountryText {
            get {
                return ResourceManager.GetString("ProductCountryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product country.
        /// </summary>
        internal static string ProductCountryTextBoxToolTip {
            get {
                return ResourceManager.GetString("ProductCountryTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string ProductCountryTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ProductCountryTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        internal static string ProductDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ProductDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string ProductDescriptionText {
            get {
                return ResourceManager.GetString("ProductDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product discount.
        /// </summary>
        internal static string ProductDiscountPlaceholder {
            get {
                return ResourceManager.GetString("ProductDiscountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount: {0} %.
        /// </summary>
        internal static string ProductDiscountText {
            get {
                return ResourceManager.GetString("ProductDiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product discount.
        /// </summary>
        internal static string ProductDiscountTextBoxToolTip {
            get {
                return ResourceManager.GetString("ProductDiscountTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string ProductDiscountTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ProductDiscountTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with the same name in current section already exists..
        /// </summary>
        internal static string ProductExistException {
            get {
                return ResourceManager.GetString("ProductExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantee: {0}.
        /// </summary>
        internal static string ProductGuaranteeText {
            get {
                return ResourceManager.GetString("ProductGuaranteeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product guarantee.
        /// </summary>
        internal static string ProductGuaranteeTextBoxToolTip {
            get {
                return ResourceManager.GetString("ProductGuaranteeTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantee.
        /// </summary>
        internal static string ProductGuaranteeTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ProductGuaranteeTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect quantity (more than 1)..
        /// </summary>
        internal static string ProductMinimumQuantityException {
            get {
                return ResourceManager.GetString("ProductMinimumQuantityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is not integer..
        /// </summary>
        internal static string ProductMinimumQuantityParseException {
            get {
                return ResourceManager.GetString("ProductMinimumQuantityParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product name.
        /// </summary>
        internal static string ProductNamePlaceholder {
            get {
                return ResourceManager.GetString("ProductNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with this name doesn&apos;t exist..
        /// </summary>
        internal static string ProductNotFoundException {
            get {
                return ResourceManager.GetString("ProductNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product price.
        /// </summary>
        internal static string ProductPricePlaceholder {
            get {
                return ResourceManager.GetString("ProductPricePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: {0} {1}.
        /// </summary>
        internal static string ProductPriceText {
            get {
                return ResourceManager.GetString("ProductPriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product price.
        /// </summary>
        internal static string ProductPriceTextBoxToolTip {
            get {
                return ResourceManager.GetString("ProductPriceTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ProductPriceTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ProductPriceTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product quantity.
        /// </summary>
        internal static string ProductQuantityPlaceholder {
            get {
                return ResourceManager.GetString("ProductQuantityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product quantity.
        /// </summary>
        internal static string ProductQuantityTextBoxToolTip {
            get {
                return ResourceManager.GetString("ProductQuantityTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string ProductQuantityTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ProductQuantityTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: {0}.
        /// </summary>
        internal static string ProductTitleText {
            get {
                return ResourceManager.GetString("ProductTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product title.
        /// </summary>
        internal static string ProductTitleTextBoxToolTip {
            get {
                return ResourceManager.GetString("ProductTitleTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ProductTitleTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("ProductTitleTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product UCN.
        /// </summary>
        internal static string ProductUcnPlaceholder {
            get {
                return ResourceManager.GetString("ProductUcnPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string QuantityButtonText {
            get {
                return ResourceManager.GetString("QuantityButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sections by product quantity.
        /// </summary>
        internal static string QuantityButtonToolTip {
            get {
                return ResourceManager.GetString("QuantityButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Order.
        /// </summary>
        internal static string QuantityButtonToolTipTitle {
            get {
                return ResourceManager.GetString("QuantityButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is not integer..
        /// </summary>
        internal static string QuantityParseException {
            get {
                return ResourceManager.GetString("QuantityParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect quantity..
        /// </summary>
        internal static string QuantityProductException {
            get {
                return ResourceManager.GetString("QuantityProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string ReportText {
            get {
                return ResourceManager.GetString("ReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter root name.
        /// </summary>
        internal static string RootNamePlaceholder {
            get {
                return ResourceManager.GetString("RootNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language Into Russian.
        /// </summary>
        internal static string RusButtonToolTip {
            get {
                return ResourceManager.GetString("RusButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string RusButtonToolTipTitle {
            get {
                return ResourceManager.GetString("RusButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files(*.csv) | *.csv.
        /// </summary>
        internal static string SaveFileFilter {
            get {
                return ResourceManager.GetString("SaveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter products.
        /// </summary>
        internal static string SearchTextBoxToolTip {
            get {
                return ResourceManager.GetString("SearchTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string SearchTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("SearchTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section with the same name in current root already exists..
        /// </summary>
        internal static string SectionExistException {
            get {
                return ResourceManager.GetString("SectionExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section with this name does not exist..
        /// </summary>
        internal static string SectionNotFoundException {
            get {
                return ResourceManager.GetString("SectionNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of these sections or tap cancel..
        /// </summary>
        internal static string SectionSelectException {
            get {
                return ResourceManager.GetString("SectionSelectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Orders.
        /// </summary>
        internal static string ShowOrdersButtonText {
            get {
                return ResourceManager.GetString("ShowOrdersButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Client&apos;s Orders.
        /// </summary>
        internal static string ShowOrdersButtonToolTip {
            get {
                return ResourceManager.GetString("ShowOrdersButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string ShowOrdersButtonToolTipTitle {
            get {
                return ResourceManager.GetString("ShowOrdersButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpThinButtonText {
            get {
                return ResourceManager.GetString("SignUpThinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting image to base64..
        /// </summary>
        internal static string StringToImgException {
            get {
                return ResourceManager.GetString("StringToImgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total payable: {0} {1}.
        /// </summary>
        internal static string TotalPayableLabelText {
            get {
                return ResourceManager.GetString("TotalPayableLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect UCN (only latin letters, digits and &quot;-&quot;)..
        /// </summary>
        internal static string UcnProductException {
            get {
                return ResourceManager.GetString("UcnProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this if you are user.
        /// </summary>
        internal static string UserButtonToolTip {
            get {
                return ResourceManager.GetString("UserButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserButtonToolTipTitle {
            get {
                return ResourceManager.GetString("UserButtonToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login.
        /// </summary>
        internal static string UserNameTextBoxToolTip {
            get {
                return ResourceManager.GetString("UserNameTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string UserNameTextBoxToolTipTitle {
            get {
                return ResourceManager.GetString("UserNameTextBoxToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse already exist. Do you want rewrite?.
        /// </summary>
        internal static string WarehouseExistWarning {
            get {
                return ResourceManager.GetString("WarehouseExistWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string WarningMessageText {
            get {
                return ResourceManager.GetString("WarningMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this if you are worker.
        /// </summary>
        internal static string WorkerButtonToolTip {
            get {
                return ResourceManager.GetString("WorkerButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string WorkerButtonToolTipTitle {
            get {
                return ResourceManager.GetString("WorkerButtonToolTipTitle", resourceCulture);
            }
        }
    }
}
